/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlbh.ui;

import com.qlbh.dao.DELIVERYDAO;
import com.qlbh.dao.QLDHDAO;
import com.qlbh.dao.QLKHODAO;
import com.qlbh.dao.RECEIPTDAO;
import com.qlbh.entity.DELIVERY;
import com.qlbh.entity.INVENTORY;
import com.qlbh.entity.QLDH;
import com.qlbh.entity.RECEIPT;
import com.qlbh.utils.MsgBox;
import com.qlbh.utils.XImage;
import com.qlbh.utils.getInfo;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class NewOrder_Details extends javax.swing.JFrame {

    /**
     * Creates new form NewOrder
     */
    public NewOrder_Details() {
        initComponents();
        this.setIconImage(XImage.getAppIcon());
        this.setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocation(DEFAULT_CURSOR, 195);
        //this.setLocationRelativeTo(null);
        this.fillComboBoxOrderID();
        this.fillComboBoxDeliveryID();
        this.fillComboBoxProductID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbo_NewOrderDetail_DeliveryID = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_NewOrder_Note = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cbo_NewOrderDetail_OrderID = new javax.swing.JComboBox<>();
        cbo_NewOrderDetail_ProductID = new javax.swing.JComboBox<>();
        txt_NewOrder_Total = new javax.swing.JTextField();
        sp_NewOrderDettail_QTY = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_OrderDetail = new rojerusan.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        btn_NewOrderDetail_add = new com.k33ptoo.components.KButton();
        btn_NewOrderDetail_edit = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NEW ORDER DETAILS");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ORDER ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DELIVERY ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("PRODUCT ID");

        cbo_NewOrderDetail_DeliveryID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("QTY");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("TOTAL");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("NOTE");

        txt_NewOrder_Note.setColumns(20);
        txt_NewOrder_Note.setRows(5);
        jScrollPane1.setViewportView(txt_NewOrder_Note);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("NEW ORDER_DETAIL");

        cbo_NewOrderDetail_OrderID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbo_NewOrderDetail_ProductID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sp_NewOrderDettail_QTY.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sp_NewOrderDettail_QTY.setPreferredSize(new java.awt.Dimension(7, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(26, 26, 26))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbo_NewOrderDetail_DeliveryID, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE)
                                        .addComponent(cbo_NewOrderDetail_OrderID, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_NewOrder_Total, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbo_NewOrderDetail_ProductID, 0, 128, Short.MAX_VALUE)
                                .addComponent(sp_NewOrderDettail_QTY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbo_NewOrderDetail_ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(cbo_NewOrderDetail_OrderID))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_NewOrderDetail_DeliveryID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_NewOrderDettail_QTY, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NewOrder_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ITEMS");

        tbl_OrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", null},
                {"", "", "", null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "QTY", "PRICE", "NOTE"
            }
        ));
        tbl_OrderDetail.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_OrderDetail.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_OrderDetail.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_OrderDetail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbl_OrderDetail.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_OrderDetail.setRowHeight(35);
        jScrollPane8.setViewportView(tbl_OrderDetail);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel2)
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btn_NewOrderDetail_add.setText("ADD");
        btn_NewOrderDetail_add.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_NewOrderDetail_add.setkEndColor(new java.awt.Color(0, 112, 192));
        btn_NewOrderDetail_add.setkHoverEndColor(new java.awt.Color(0, 30, 153));
        btn_NewOrderDetail_add.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_NewOrderDetail_add.setkHoverStartColor(new java.awt.Color(0, 30, 153));
        btn_NewOrderDetail_add.setkPressedColor(new java.awt.Color(153, 153, 153));
        btn_NewOrderDetail_add.setkStartColor(new java.awt.Color(0, 79, 174));
        btn_NewOrderDetail_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewOrderDetail_addActionPerformed(evt);
            }
        });
        jPanel4.add(btn_NewOrderDetail_add);

        btn_NewOrderDetail_edit.setText("EDIT");
        btn_NewOrderDetail_edit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_NewOrderDetail_edit.setkEndColor(new java.awt.Color(0, 112, 192));
        btn_NewOrderDetail_edit.setkHoverEndColor(new java.awt.Color(0, 30, 153));
        btn_NewOrderDetail_edit.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_NewOrderDetail_edit.setkHoverStartColor(new java.awt.Color(0, 30, 153));
        btn_NewOrderDetail_edit.setkPressedColor(new java.awt.Color(153, 153, 153));
        btn_NewOrderDetail_edit.setkStartColor(new java.awt.Color(0, 79, 174));
        btn_NewOrderDetail_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewOrderDetail_editActionPerformed(evt);
            }
        });
        jPanel4.add(btn_NewOrderDetail_edit);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(426, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NewOrderDetail_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewOrderDetail_addActionPerformed
        // TODO add your handling code here:
        RECEIPT receipt = getForm();
        if (receipt != null) {
            if (receiptdao.selectebyID(receipt.getMADH()) == null) {
                receiptdao.insert(receipt);
                MsgBox.alert(this, "Insert Successfully!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "This receipt already exist!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_NewOrderDetail_addActionPerformed

    private void btn_NewOrderDetail_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewOrderDetail_editActionPerformed
        // TODO add your handling code here:
        RECEIPT receipt = getForm();
        if (receipt != null) {
            if (receiptdao.selectebyID(receipt.getMADH()) != null) {
                receiptdao.update(receipt);
                MsgBox.alert(this, "Update Successfully!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "This receipt doesn't exist!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_NewOrderDetail_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrder_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrder_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrder_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrder_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewOrder_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_NewOrderDetail_add;
    private com.k33ptoo.components.KButton btn_NewOrderDetail_edit;
    private javax.swing.JComboBox<String> cbo_NewOrderDetail_DeliveryID;
    private javax.swing.JComboBox<String> cbo_NewOrderDetail_OrderID;
    private javax.swing.JComboBox<String> cbo_NewOrderDetail_ProductID;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSpinner sp_NewOrderDettail_QTY;
    private rojerusan.RSTableMetro tbl_OrderDetail;
    private javax.swing.JTextArea txt_NewOrder_Note;
    private javax.swing.JTextField txt_NewOrder_Total;
    // End of variables declaration//GEN-END:variables

    QLDHDAO qldhdao = new QLDHDAO();
    DELIVERYDAO delidao = new DELIVERYDAO();
    QLKHODAO qlkhodao = new QLKHODAO();
    RECEIPTDAO receiptdao = new RECEIPTDAO();
    int qty = 0;

    public void fillToForm() {
        RECEIPT receipt = getInfo.receipt;
        if (receipt != null) {
            cbo_NewOrderDetail_OrderID.getModel().setSelectedItem(receipt.getMADH());
            cbo_NewOrderDetail_DeliveryID.getModel().setSelectedItem(receipt.getMAVanChuyen());
            cbo_NewOrderDetail_ProductID.getModel().setSelectedItem(receipt.getMASP());
            sp_NewOrderDettail_QTY.setValue(receipt.getSOLUONG());
            txt_NewOrder_Note.setText(receipt.getGHICHU());
            txt_NewOrder_Total.setText(String.valueOf(receiptdao.getTotal(receipt.getMADH())));
            fillTableOrderDetail();
        }
    }

    private void fillTableOrderDetail() {
        DefaultTableModel model = (DefaultTableModel) tbl_OrderDetail.getModel();
        model.setRowCount(0);
        try {
            List<Object[]> list = receiptdao.getOrderTableByKeyword(String.valueOf(cbo_NewOrderDetail_OrderID.getSelectedItem()));
            for (Object[] row : list) {
                if (row[3] != null) {
                    model.addRow(new Object[]{row[3], row[4], row[6], row[7], row[8]});
                }
            }
            
        } catch (Exception e) {

        }
    }

    private void fillComboBoxOrderID() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_NewOrderDetail_OrderID.getModel();
        model.removeAllElements();
        List<QLDH> list = qldhdao.selectAll();
        for (QLDH item : list) {
            model.addElement(item);
        }
    }

    private void fillComboBoxDeliveryID() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_NewOrderDetail_DeliveryID.getModel();
        model.removeAllElements();
        List<DELIVERY> list = delidao.selectAll();
        for (DELIVERY item : list) {
            model.addElement(item);
        }
    }

    private void fillComboBoxProductID() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_NewOrderDetail_ProductID.getModel();
        model.removeAllElements();
        List<INVENTORY> list = qlkhodao.selectAll();
        for (INVENTORY item : list) {
            model.addElement(item);
        }
    }

    private boolean validateForm() {
        String Error = "";
        int qty = sp_NewOrderDettail_QTY.getValue().hashCode();
        if (qty <= 0) {
            Error += "The QTY is not equal to 0 ! \n";
        }
        if (!Error.equals("")) {
            JOptionPane.showMessageDialog(this, Error, "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void clearAll() {
        sp_NewOrderDettail_QTY.setValue(0);
        txt_NewOrder_Total.setText("");
        txt_NewOrder_Note.setText("");
    }

    private RECEIPT getForm() {
        RECEIPT receipt = new RECEIPT();
        if (validateForm()) {
            receipt.setMADH(String.valueOf(cbo_NewOrderDetail_OrderID.getSelectedItem()));
            receipt.setMAVanChuyen(String.valueOf(cbo_NewOrderDetail_DeliveryID.getSelectedItem()));
            receipt.setMASP(String.valueOf(cbo_NewOrderDetail_ProductID.getSelectedItem()));
            receipt.setSOLUONG(sp_NewOrderDettail_QTY.getValue().hashCode());
            receipt.setGHICHU(txt_NewOrder_Note.getText());
        } else {
            return null;
        }
        return receipt;
    }

    private void setForm(RECEIPT receipt) {
        cbo_NewOrderDetail_OrderID.setSelectedItem(receipt.getMADH());
        cbo_NewOrderDetail_DeliveryID.setSelectedItem(receipt.getMAVanChuyen());
        cbo_NewOrderDetail_ProductID.setSelectedItem(receipt.getMASP());
        sp_NewOrderDettail_QTY.setValue(receipt.getSOLUONG());
        txt_NewOrder_Note.setText(receipt.getGHICHU());
        txt_NewOrder_Total.setText(String.valueOf(receiptdao.getTotal(receipt.getMADH())));
    }

    public void setEnableButton(String addorEdit) {
        if (addorEdit.equalsIgnoreCase("add")) {
            btn_NewOrderDetail_add.setEnabled(true);
            btn_NewOrderDetail_add.setVisible(true);
            btn_NewOrderDetail_edit.setEnabled(false);
            btn_NewOrderDetail_edit.setVisible(false);
            txt_NewOrder_Total.setEditable(false);
            cbo_NewOrderDetail_OrderID.setEnabled(true);
            clearAll();
        } else if (addorEdit.equalsIgnoreCase("edit")) {
            btn_NewOrderDetail_add.setEnabled(false);
            btn_NewOrderDetail_add.setVisible(false);
            btn_NewOrderDetail_edit.setEnabled(true);
            btn_NewOrderDetail_edit.setVisible(true);
            txt_NewOrder_Total.setEditable(false);
            cbo_NewOrderDetail_OrderID.setEnabled(false);
        }
    }
}
