/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;

import com.qlrp.dao.QLDADAO;
import com.qlrp.dao.QLKICHCOVALOAIDAO;
import com.qlrp.entity.DOAN;
import com.qlrp.entity.KICHCODA;
import com.qlrp.entity.PHIM;
import com.qlrp.utils.XImage;
import java.awt.Color;
import java.io.File;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author HAN-PC
 */
public class ChiTietDoAn extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietDoAn
     */
    public ChiTietDoAn() {
        initComponents();
        init();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_HinhDoAn = new javax.swing.JLabel();
        txt_TenDoAn = new javax.swing.JTextPane();
        pnl_KhoiChieu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Gia = new javax.swing.JLabel();
        pnl_KhoiChieu1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbo_KichCo = new rojerusan.RSComboMetro();
        pnl_KhoiChieu2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sp_SoLuong = new javax.swing.JSpinner();
        pnl_KhoiChieu3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_TinhTrang = new javax.swing.JLabel();
        btn_ThemVaoGioHang = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/close.png"))); // NOI18N
        lbl_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ExitMouseClicked(evt);
            }
        });

        lbl_HinhDoAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/do an/bap caramel.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HinhDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HinhDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txt_TenDoAn.setEditable(false);
        txt_TenDoAn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_TenDoAn.setText("BẮP RANG BƠ");
        txt_TenDoAn.setFocusable(false);
        txt_TenDoAn.setOpaque(false);

        pnl_KhoiChieu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("GIÁ:");

        lbl_Gia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Gia.setText("35.000 VNĐ");

        javax.swing.GroupLayout pnl_KhoiChieuLayout = new javax.swing.GroupLayout(pnl_KhoiChieu);
        pnl_KhoiChieu.setLayout(pnl_KhoiChieuLayout);
        pnl_KhoiChieuLayout.setHorizontalGroup(
            pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieuLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Gia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_KhoiChieuLayout.setVerticalGroup(
            pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieuLayout.createSequentialGroup()
                .addGroup(pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pnl_KhoiChieu1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("KÍCH CỠ:");

        cbo_KichCo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnl_KhoiChieu1Layout = new javax.swing.GroupLayout(pnl_KhoiChieu1);
        pnl_KhoiChieu1.setLayout(pnl_KhoiChieu1Layout);
        pnl_KhoiChieu1Layout.setHorizontalGroup(
            pnl_KhoiChieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbo_KichCo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_KhoiChieu1Layout.setVerticalGroup(
            pnl_KhoiChieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbo_KichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_KhoiChieu2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("SỐ LƯỢNG:");

        sp_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sp_SoLuong.setPreferredSize(new java.awt.Dimension(7, 20));
        sp_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sp_SoLuongKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnl_KhoiChieu2Layout = new javax.swing.GroupLayout(pnl_KhoiChieu2);
        pnl_KhoiChieu2.setLayout(pnl_KhoiChieu2Layout);
        pnl_KhoiChieu2Layout.setHorizontalGroup(
            pnl_KhoiChieu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(sp_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_KhoiChieu2Layout.setVerticalGroup(
            pnl_KhoiChieu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu2Layout.createSequentialGroup()
                .addGroup(pnl_KhoiChieu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_KhoiChieu2Layout.createSequentialGroup()
                        .addComponent(sp_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_KhoiChieu2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnl_KhoiChieu3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("TÌNH TRẠNG:");

        lbl_TinhTrang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TinhTrang.setText("CÒN HÀNG");

        javax.swing.GroupLayout pnl_KhoiChieu3Layout = new javax.swing.GroupLayout(pnl_KhoiChieu3);
        pnl_KhoiChieu3.setLayout(pnl_KhoiChieu3Layout);
        pnl_KhoiChieu3Layout.setHorizontalGroup(
            pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lbl_TinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );
        pnl_KhoiChieu3Layout.setVerticalGroup(
            pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_ThemVaoGioHang.setText("THÊM VÀO GIỎ HÀNG");
        btn_ThemVaoGioHang.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(805, Short.MAX_VALUE)
                        .addComponent(lbl_Exit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pnl_KhoiChieu2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl_KhoiChieu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(pnl_KhoiChieu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_TenDoAn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(pnl_KhoiChieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(btn_ThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Exit)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_TenDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_KhoiChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnl_KhoiChieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(pnl_KhoiChieu2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnl_KhoiChieu3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 847, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File f = new File("");
    List<DOAN> listda = null;
    List<KICHCODA> listKCDA = null;
    QLDADAO qldadao = new QLDADAO();
    QLKICHCOVALOAIDAO qlkichcovaloaidao = new QLKICHCOVALOAIDAO();

    private void init() {
        this.setIconImage(XImage.getAppIcon());
        designTextPane(txt_TenDoAn);
    }

    private void designTextPane(JTextPane txt) {
        txt.setOpaque(false);
        txt.setBorder(BorderFactory.createEmptyBorder());
        txt.setBackground(new Color(0, 0, 0, 0));

        StyledDocument style = txt.getStyledDocument();
        SimpleAttributeSet align = new SimpleAttributeSet();
        StyleConstants.setAlignment(align, StyleConstants.ALIGN_CENTER);
        style.setParagraphAttributes(0, style.getLength(), align, false);
    }

    private void fillToComboboxKichCo() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_KichCo.getModel();
        cbo_KichCo.removeAllItems();
        listKCDA = qlkichcovaloaidao.selectAllKichCo();
        for (KICHCODA kc : listKCDA) {
            model.addElement(kc.getTEN_KICH_CO_DA());
        }
    }

    public void fillToChiTietDoAn(DOAN da) {
        txt_TenDoAn.setText(da.getTENDOAN().toUpperCase());
        DecimalFormat formatter = new DecimalFormat("###,###,###");
        lbl_Gia.setText(formatter.format(da.getDONGIA())+" VNĐ");
        if (da.getSOLUONG() == 0) {
            lbl_TinhTrang.setText("HẾT HÀNG");
            lbl_TinhTrang.setForeground(Color.RED);
        } else {
            lbl_TinhTrang.setText("CÒN " + da.getSOLUONG() + " MÓN");
            lbl_TinhTrang.setForeground(Color.BLACK);
        }

        fillToComboboxKichCo();

        try {
            String duongdanBanner = f.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\DOAN\\";
            lbl_HinhDoAn.setIcon(XImage.ResizeImage(lbl_HinhDoAn.getWidth(), lbl_HinhDoAn.getHeight(), duongdanBanner + da.getHINH()));
        } catch (Exception e) {
        }
    }

    private void lbl_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lbl_ExitMouseClicked

    private void sp_SoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sp_SoLuongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sp_SoLuongKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietDoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietDoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietDoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietDoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietDoAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_ThemVaoGioHang;
    private rojerusan.RSComboMetro cbo_KichCo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Exit;
    private javax.swing.JLabel lbl_Gia;
    private javax.swing.JLabel lbl_HinhDoAn;
    private javax.swing.JLabel lbl_TinhTrang;
    private javax.swing.JPanel pnl_KhoiChieu;
    private javax.swing.JPanel pnl_KhoiChieu1;
    private javax.swing.JPanel pnl_KhoiChieu2;
    private javax.swing.JPanel pnl_KhoiChieu3;
    private javax.swing.JSpinner sp_SoLuong;
    private javax.swing.JTextPane txt_TenDoAn;
    // End of variables declaration//GEN-END:variables
}
