/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;



import com.qlrp.dao.QLSUATCHIEUDAO;
import com.qlrp.entity.SUATCHIEU;
import com.qlrp.utils.MsgBox;
import com.qlrp.utils.getInfo;
import java.io.File;
import java.sql.Time;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author duong
 */
public class ChitietSC extends javax.swing.JFrame {

    /**
     * Creates new form NewMovie
     */
    File f = new File("");
    QLSUATCHIEUDAO qlsuatchieudao = new QLSUATCHIEUDAO();
    List<SUATCHIEU> listSC = qlsuatchieudao.selectAll();

    public ChitietSC() {
        initComponents();
        init();
    }

    private void init() {
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);     
    }

    public void fillToForm() {
        SUATCHIEU sc = getInfo.sc;
        if (sc != null) {
            txt_maSC.setText(sc.getMA_SUAT_CHIEU());
            txt_MaPC1.setText(sc.getMA_PHONG_CHIEU());
            txt_ddphim.setText(sc.getTEN_DINH_DANG_PHIM());
            txt_Maphim.setText(sc.getMA_PHIM());
            dc_GioBD.setDate(sc.getGIO_BAT_DAU());
            dc_GioKT.setDate(sc.getGIO_KET_THUC());
            dc_ngaychieu.setDate(sc.getNGAY_CHIEU());             
        }
    }

    private void clearAll() {
        txt_maSC.setText("");
        txt_MaPC1.setText("");
        txt_ddphim.setText("");
        txt_Maphim.setText("");
        dc_GioBD.setDate(null);
        dc_GioKT.setDate(null);
        dc_ngaychieu.setDate(null);
    }

    public void setForm(SUATCHIEU sc) {
         try {
            txt_maSC.setText(sc.getMA_SUAT_CHIEU());
            txt_MaPC1.setText(sc.getMA_PHONG_CHIEU());
            txt_ddphim.setText(sc.getTEN_DINH_DANG_PHIM());
            txt_Maphim.setText(sc.getMA_PHIM());
            dc_GioBD.setDate(sc.getGIO_BAT_DAU());
            dc_GioKT.setDate(sc.getGIO_KET_THUC());
            dc_ngaychieu.setDate(sc.getNGAY_CHIEU());
        } catch (Exception e) {
        }
    }
    
    String masuatchieu;

    private SUATCHIEU getForm() {
        SUATCHIEU sc = new SUATCHIEU();
        if (validateForm()) {
            sc.setMA_SUAT_CHIEU(txt_maSC.getText());
            sc.setMA_PHONG_CHIEU(txt_MaPC1.getText());
            sc.setTEN_DINH_DANG_PHIM(txt_ddphim.getText());
            sc.setMA_PHIM(txt_Maphim.getText());
            sc.setGIO_BAT_DAU((Time) dc_GioBD.getDate());
            sc.setGIO_KET_THUC((Time) dc_GioKT.getDate());
            sc.setNGAY_CHIEU(dc_ngaychieu.getDate());
        } else {
            return null;
        }
        return sc;
        
    }
    
     public void setEnableButton(String addorEdit) {
        if (addorEdit.equalsIgnoreCase("add")) {
            btn_edit.setEnabled(false);
            btn_edit.setVisible(false);
            btn_Delete.setEnabled(false);
            btn_Delete.setVisible(false);
            clearAll();
        } else if (addorEdit.equalsIgnoreCase("edit")) {
            btn_edit.setEnabled(true);
            btn_edit.setVisible(true);
            btn_Delete.setEnabled(true);
            btn_Delete.setVisible(true);
        }
    }

    private boolean validateForm() {
        return false;
        
    }

    

    private void clearform() {
        txt_maSC.setText("");
        txt_MaPC1.setText("");
        txt_ddphim.setText("");
        txt_Maphim.setText("");
        dc_GioBD.setDate(null);
        dc_GioKT.setDate(null);
        dc_ngaychieu.setDate(null);
    }

    void insert() {
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_ten3 = new javax.swing.JLabel();
        lbl_ten6 = new javax.swing.JLabel();
        lbl_ten10 = new javax.swing.JLabel();
        txt_maSC = new javax.swing.JTextField();
        lbl_ten8 = new javax.swing.JLabel();
        dc_GioBD = new newscomponents.RSDateChooserModern();
        lbl_ten9 = new javax.swing.JLabel();
        lbl_ten11 = new javax.swing.JLabel();
        txt_ddphim = new javax.swing.JTextField();
        lbl_ten12 = new javax.swing.JLabel();
        btn_Delete = new rsbuttongradiente.RSButtonGradiente();
        btn_edit = new rsbuttongradiente.RSButtonGradiente();
        txt_Maphim = new javax.swing.JTextField();
        dc_ngaychieu = new newscomponents.RSDateChooserModern();
        dc_GioKT = new newscomponents.RSDateChooserModern();
        txt_MaPC1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ten3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ten3.setText("NGÀY CHIẾU");
        jPanel2.add(lbl_ten3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 150, 40));

        lbl_ten6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ten6.setText("MÃ PHÒNG CHIẾU");
        jPanel2.add(lbl_ten6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 40));

        lbl_ten10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ten10.setText("MÃ SUẤT CHIẾU");
        jPanel2.add(lbl_ten10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 40));

        txt_maSC.setEditable(false);
        jPanel2.add(txt_maSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 328, 40));

        lbl_ten8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ten8.setText("MÃ PHIM");
        jPanel2.add(lbl_ten8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 40));

        dc_GioBD.setBackground(new java.awt.Color(102, 102, 255));
        dc_GioBD.setFormatDate("hh:mm:ss");
        jPanel2.add(dc_GioBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 328, 40));

        lbl_ten9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ten9.setText("TÊN ĐỊNH DẠNG PHIM");
        jPanel2.add(lbl_ten9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 40));

        lbl_ten11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ten11.setText("GIỜ KẾT THÚC");
        jPanel2.add(lbl_ten11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, 40));
        jPanel2.add(txt_ddphim, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 328, 40));

        lbl_ten12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ten12.setText("GIỜ BẮT ĐẦU");
        jPanel2.add(lbl_ten12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 40));

        btn_Delete.setText("XÓA");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 150, 40));

        btn_edit.setText("SỬA");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel2.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 150, 40));

        txt_Maphim.setEditable(false);
        jPanel2.add(txt_Maphim, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 328, 40));

        dc_ngaychieu.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.add(dc_ngaychieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 328, 40));

        dc_GioKT.setBackground(new java.awt.Color(102, 102, 255));
        dc_GioKT.setFormatDate("hh:mm:ss");
        jPanel2.add(dc_GioKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 328, 40));

        txt_MaPC1.setEditable(false);
        jPanel2.add(txt_MaPC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 328, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SUẤT CHIẾU");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
       if (btn_edit.isEnabled()) {
            if (txt_maSC.getText() != null && !txt_maSC.getText().equals("")) {
                if (qlsuatchieudao.selectebyID(txt_maSC.getText()) != null) {
                    qlsuatchieudao.delete(txt_maSC.getText());
                    MsgBox.alert(this, "Xóa thành công!");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Suat chieu không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tên bộ phim không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            MsgBox.alert(this, "You can only Add. If you want to edit, please choose again!");
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if (btn_edit.isEnabled()) {
            SUATCHIEU sc = getForm();
            if (sc != null) {
                if (qlsuatchieudao.selectebyID(sc.getMA_SUAT_CHIEU()) != null) {
                    qlsuatchieudao.update(sc);
                    MsgBox.alert(this, "Cập nhật thành công!");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Suat chieu này không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            MsgBox.alert(this, "You can only Add. If you want to edit, please choose again!");
        }
    }//GEN-LAST:event_btn_editActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChitietSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChitietSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChitietSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChitietSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChitietSC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttongradiente.RSButtonGradiente btn_Delete;
    private rsbuttongradiente.RSButtonGradiente btn_edit;
    private newscomponents.RSDateChooserModern dc_GioBD;
    private newscomponents.RSDateChooserModern dc_GioKT;
    private newscomponents.RSDateChooserModern dc_ngaychieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_ten10;
    private javax.swing.JLabel lbl_ten11;
    private javax.swing.JLabel lbl_ten12;
    private javax.swing.JLabel lbl_ten3;
    private javax.swing.JLabel lbl_ten6;
    private javax.swing.JLabel lbl_ten8;
    private javax.swing.JLabel lbl_ten9;
    private javax.swing.JTextField txt_MaPC1;
    private javax.swing.JTextField txt_Maphim;
    private javax.swing.JTextField txt_ddphim;
    private javax.swing.JTextField txt_maSC;
    // End of variables declaration//GEN-END:variables
}
