/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;

import com.qlrp.dao.QLGHENGOIDAO;
import com.qlrp.dao.QLPHONGCHIEUDAO;
import com.qlrp.entity.GHENGOI;
import com.qlrp.entity.LOAIGHE;
import com.qlrp.entity.PHIM;
import com.qlrp.entity.PHONGCHIEU;
import com.qlrp.entity.SUATCHIEU;
import static com.qlrp.ui.DatVe.Instance;
import com.qlrp.utils.XImage;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import rojeru_san.RSButton;

/**
 *
 * @author HAN-PC
 */
public class ChonChoNgoi extends javax.swing.JFrame {

    /**
     * Creates new form ChonChoNgoi
     */
    public ChonChoNgoi() {
        initComponents();
        init();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_Cot = new javax.swing.JPanel();
        rSButton248 = new rojeru_san.RSButton();
        rSButton249 = new rojeru_san.RSButton();
        rSButton250 = new rojeru_san.RSButton();
        rSButton251 = new rojeru_san.RSButton();
        rSButton252 = new rojeru_san.RSButton();
        rSButton253 = new rojeru_san.RSButton();
        rSButton254 = new rojeru_san.RSButton();
        rSButton255 = new rojeru_san.RSButton();
        rSButton256 = new rojeru_san.RSButton();
        rSButton257 = new rojeru_san.RSButton();
        rSButton258 = new rojeru_san.RSButton();
        rSButton259 = new rojeru_san.RSButton();
        rSButton260 = new rojeru_san.RSButton();
        rSButton261 = new rojeru_san.RSButton();
        rSButton262 = new rojeru_san.RSButton();
        rSButton263 = new rojeru_san.RSButton();
        rSButton264 = new rojeru_san.RSButton();
        rSButton265 = new rojeru_san.RSButton();
        rSButton266 = new rojeru_san.RSButton();
        pnl_Hang = new javax.swing.JPanel();
        rSButton221 = new rojeru_san.RSButton();
        rSButton222 = new rojeru_san.RSButton();
        rSButton223 = new rojeru_san.RSButton();
        rSButton224 = new rojeru_san.RSButton();
        rSButton225 = new rojeru_san.RSButton();
        rSButton226 = new rojeru_san.RSButton();
        rSButton227 = new rojeru_san.RSButton();
        rSButton228 = new rojeru_san.RSButton();
        rSButton229 = new rojeru_san.RSButton();
        rSButton230 = new rojeru_san.RSButton();
        rSButton231 = new rojeru_san.RSButton();
        rSButton232 = new rojeru_san.RSButton();
        pnl_ShowGhe = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbl_GiaVeThuong = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_HinhGheThuong = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_GiaVeVIP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_HinhGheVIP = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_GiaVeCouple = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_HinhGheCouple = new javax.swing.JLabel();
        rSButton217 = new rojeru_san.RSButton();
        rSButton218 = new rojeru_san.RSButton();
        rSButton219 = new rojeru_san.RSButton();
        rSButton220 = new rojeru_san.RSButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txt_Tenfilm = new javax.swing.JTextPane();
        jPanel11 = new javax.swing.JPanel();
        txt_ChoNgoi = new javax.swing.JTextPane();
        jPanel12 = new javax.swing.JPanel();
        txt_ThoiGianChieu = new javax.swing.JTextPane();
        jPanel13 = new javax.swing.JPanel();
        txt_TongTien = new javax.swing.JTextPane();
        lbl_PhongChieu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHỌN CHỖ NGỒI");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("MÀN HÌNH CHIẾU PHIM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnl_Cot.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Cot.setLayout(new java.awt.GridLayout(1, 19, 10, 10));

        rSButton248.setBackground(new java.awt.Color(255, 255, 255));
        rSButton248.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton248.setForeground(new java.awt.Color(0, 0, 0));
        rSButton248.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton248.setColorText(new java.awt.Color(0, 0, 0));
        rSButton248.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton248.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton248);

        rSButton249.setBackground(new java.awt.Color(255, 255, 255));
        rSButton249.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton249.setForeground(new java.awt.Color(0, 0, 0));
        rSButton249.setText("1");
        rSButton249.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton249.setColorText(new java.awt.Color(0, 0, 0));
        rSButton249.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton249.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton249);

        rSButton250.setBackground(new java.awt.Color(255, 255, 255));
        rSButton250.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton250.setForeground(new java.awt.Color(0, 0, 0));
        rSButton250.setText("2");
        rSButton250.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton250.setColorText(new java.awt.Color(0, 0, 0));
        rSButton250.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton250.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton250);

        rSButton251.setBackground(new java.awt.Color(255, 255, 255));
        rSButton251.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton251.setForeground(new java.awt.Color(0, 0, 0));
        rSButton251.setText("3");
        rSButton251.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton251.setColorText(new java.awt.Color(0, 0, 0));
        rSButton251.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton251.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton251);

        rSButton252.setBackground(new java.awt.Color(255, 255, 255));
        rSButton252.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton252.setForeground(new java.awt.Color(0, 0, 0));
        rSButton252.setText("4");
        rSButton252.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton252.setColorText(new java.awt.Color(0, 0, 0));
        rSButton252.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton252.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton252);

        rSButton253.setBackground(new java.awt.Color(255, 255, 255));
        rSButton253.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton253.setForeground(new java.awt.Color(0, 0, 0));
        rSButton253.setText("5");
        rSButton253.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton253.setColorText(new java.awt.Color(0, 0, 0));
        rSButton253.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton253.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton253);

        rSButton254.setBackground(new java.awt.Color(255, 255, 255));
        rSButton254.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton254.setForeground(new java.awt.Color(0, 0, 0));
        rSButton254.setText("6");
        rSButton254.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton254.setColorText(new java.awt.Color(0, 0, 0));
        rSButton254.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton254.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton254);

        rSButton255.setBackground(new java.awt.Color(255, 255, 255));
        rSButton255.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton255.setForeground(new java.awt.Color(0, 0, 0));
        rSButton255.setText("7");
        rSButton255.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton255.setColorText(new java.awt.Color(0, 0, 0));
        rSButton255.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton255.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton255);

        rSButton256.setBackground(new java.awt.Color(255, 255, 255));
        rSButton256.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton256.setForeground(new java.awt.Color(0, 0, 0));
        rSButton256.setText("8");
        rSButton256.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton256.setColorText(new java.awt.Color(0, 0, 0));
        rSButton256.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton256.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton256);

        rSButton257.setBackground(new java.awt.Color(255, 255, 255));
        rSButton257.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton257.setForeground(new java.awt.Color(0, 0, 0));
        rSButton257.setText("9");
        rSButton257.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton257.setColorText(new java.awt.Color(0, 0, 0));
        rSButton257.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton257.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton257);

        rSButton258.setBackground(new java.awt.Color(255, 255, 255));
        rSButton258.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton258.setForeground(new java.awt.Color(0, 0, 0));
        rSButton258.setText("10");
        rSButton258.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton258.setColorText(new java.awt.Color(0, 0, 0));
        rSButton258.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton258.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton258);

        rSButton259.setBackground(new java.awt.Color(255, 255, 255));
        rSButton259.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton259.setForeground(new java.awt.Color(0, 0, 0));
        rSButton259.setText("11");
        rSButton259.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton259.setColorText(new java.awt.Color(0, 0, 0));
        rSButton259.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton259.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton259);

        rSButton260.setBackground(new java.awt.Color(255, 255, 255));
        rSButton260.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton260.setForeground(new java.awt.Color(0, 0, 0));
        rSButton260.setText("12");
        rSButton260.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton260.setColorText(new java.awt.Color(0, 0, 0));
        rSButton260.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton260.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton260);

        rSButton261.setBackground(new java.awt.Color(255, 255, 255));
        rSButton261.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton261.setForeground(new java.awt.Color(0, 0, 0));
        rSButton261.setText("13");
        rSButton261.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton261.setColorText(new java.awt.Color(0, 0, 0));
        rSButton261.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton261.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton261);

        rSButton262.setBackground(new java.awt.Color(255, 255, 255));
        rSButton262.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton262.setForeground(new java.awt.Color(0, 0, 0));
        rSButton262.setText("14");
        rSButton262.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton262.setColorText(new java.awt.Color(0, 0, 0));
        rSButton262.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton262.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton262);

        rSButton263.setBackground(new java.awt.Color(255, 255, 255));
        rSButton263.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton263.setForeground(new java.awt.Color(0, 0, 0));
        rSButton263.setText("15");
        rSButton263.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton263.setColorText(new java.awt.Color(0, 0, 0));
        rSButton263.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton263.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton263);

        rSButton264.setBackground(new java.awt.Color(255, 255, 255));
        rSButton264.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton264.setForeground(new java.awt.Color(0, 0, 0));
        rSButton264.setText("16");
        rSButton264.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton264.setColorText(new java.awt.Color(0, 0, 0));
        rSButton264.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton264.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton264);

        rSButton265.setBackground(new java.awt.Color(255, 255, 255));
        rSButton265.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton265.setForeground(new java.awt.Color(0, 0, 0));
        rSButton265.setText("17");
        rSButton265.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton265.setColorText(new java.awt.Color(0, 0, 0));
        rSButton265.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton265.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton265);

        rSButton266.setBackground(new java.awt.Color(255, 255, 255));
        rSButton266.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton266.setForeground(new java.awt.Color(0, 0, 0));
        rSButton266.setText("18");
        rSButton266.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton266.setColorText(new java.awt.Color(0, 0, 0));
        rSButton266.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton266.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Cot.add(rSButton266);

        pnl_Hang.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Hang.setLayout(new java.awt.GridLayout(12, 1, 10, 10));

        rSButton221.setBackground(new java.awt.Color(255, 255, 255));
        rSButton221.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton221.setForeground(new java.awt.Color(0, 0, 0));
        rSButton221.setText("A");
        rSButton221.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton221.setColorText(new java.awt.Color(0, 0, 0));
        rSButton221.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton221.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton221);

        rSButton222.setBackground(new java.awt.Color(255, 255, 255));
        rSButton222.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton222.setForeground(new java.awt.Color(0, 0, 0));
        rSButton222.setText("B");
        rSButton222.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton222.setColorText(new java.awt.Color(0, 0, 0));
        rSButton222.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton222.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton222);

        rSButton223.setBackground(new java.awt.Color(255, 255, 255));
        rSButton223.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton223.setForeground(new java.awt.Color(0, 0, 0));
        rSButton223.setText("C");
        rSButton223.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton223.setColorText(new java.awt.Color(0, 0, 0));
        rSButton223.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton223.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton223);

        rSButton224.setBackground(new java.awt.Color(255, 255, 255));
        rSButton224.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton224.setForeground(new java.awt.Color(0, 0, 0));
        rSButton224.setText("D");
        rSButton224.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton224.setColorText(new java.awt.Color(0, 0, 0));
        rSButton224.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton224.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton224);

        rSButton225.setBackground(new java.awt.Color(255, 255, 255));
        rSButton225.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton225.setForeground(new java.awt.Color(0, 0, 0));
        rSButton225.setText("E");
        rSButton225.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton225.setColorText(new java.awt.Color(0, 0, 0));
        rSButton225.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton225.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton225);

        rSButton226.setBackground(new java.awt.Color(255, 255, 255));
        rSButton226.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton226.setForeground(new java.awt.Color(0, 0, 0));
        rSButton226.setText("F");
        rSButton226.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton226.setColorText(new java.awt.Color(0, 0, 0));
        rSButton226.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton226.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton226);

        rSButton227.setBackground(new java.awt.Color(255, 255, 255));
        rSButton227.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton227.setForeground(new java.awt.Color(0, 0, 0));
        rSButton227.setText("G");
        rSButton227.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton227.setColorText(new java.awt.Color(0, 0, 0));
        rSButton227.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton227.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton227);

        rSButton228.setBackground(new java.awt.Color(255, 255, 255));
        rSButton228.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton228.setForeground(new java.awt.Color(0, 0, 0));
        rSButton228.setText("H");
        rSButton228.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton228.setColorText(new java.awt.Color(0, 0, 0));
        rSButton228.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton228.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton228);

        rSButton229.setBackground(new java.awt.Color(255, 255, 255));
        rSButton229.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton229.setForeground(new java.awt.Color(0, 0, 0));
        rSButton229.setText("I");
        rSButton229.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton229.setColorText(new java.awt.Color(0, 0, 0));
        rSButton229.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton229.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton229);

        rSButton230.setBackground(new java.awt.Color(255, 255, 255));
        rSButton230.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton230.setForeground(new java.awt.Color(0, 0, 0));
        rSButton230.setText("J");
        rSButton230.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton230.setColorText(new java.awt.Color(0, 0, 0));
        rSButton230.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton230.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton230);

        rSButton231.setBackground(new java.awt.Color(255, 255, 255));
        rSButton231.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton231.setForeground(new java.awt.Color(0, 0, 0));
        rSButton231.setText("K");
        rSButton231.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton231.setColorText(new java.awt.Color(0, 0, 0));
        rSButton231.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton231.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton231);

        rSButton232.setBackground(new java.awt.Color(255, 255, 255));
        rSButton232.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton232.setForeground(new java.awt.Color(0, 0, 0));
        rSButton232.setText("L");
        rSButton232.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton232.setColorText(new java.awt.Color(0, 0, 0));
        rSButton232.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton232.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        pnl_Hang.add(rSButton232);

        pnl_ShowGhe.setBackground(new java.awt.Color(255, 255, 255));
        pnl_ShowGhe.setLayout(new java.awt.GridLayout(12, 18, 10, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lbl_GiaVeThuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_GiaVeThuong.setText("80,000 VNĐ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("GIÁ VÉ:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("GHẾ THƯỜNG");

        lbl_HinhGheThuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/loaighe/ghethuong.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_HinhGheThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_GiaVeThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_HinhGheThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_GiaVeThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lbl_GiaVeVIP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_GiaVeVIP.setText("120,000 VNĐ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("GIÁ VÉ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("GHẾ VIP");

        lbl_HinhGheVIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/loaighe/GheVIP.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_HinhGheVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_GiaVeVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_HinhGheVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_GiaVeVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lbl_GiaVeCouple.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_GiaVeCouple.setText("300,000 VNĐ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("GIÁ VÉ:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("GHẾ VIP COUPLE");

        lbl_HinhGheCouple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/loaighe/GheVipCouple.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_HinhGheCouple, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_GiaVeCouple, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_HinhGheCouple, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_GiaVeCouple, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        rSButton217.setBackground(new java.awt.Color(0, 0, 204));
        rSButton217.setBorder(null);
        rSButton217.setColorHover(new java.awt.Color(0, 0, 153));

        rSButton218.setBackground(new java.awt.Color(255, 0, 0));
        rSButton218.setBorder(null);
        rSButton218.setColorHover(new java.awt.Color(255, 102, 102));

        rSButton219.setBackground(new java.awt.Color(255, 204, 0));
        rSButton219.setBorder(null);
        rSButton219.setColorHover(new java.awt.Color(204, 204, 0));

        rSButton220.setBackground(new java.awt.Color(0, 153, 0));
        rSButton220.setBorder(null);
        rSButton220.setColorHover(new java.awt.Color(0, 102, 0));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel14.setText("ĐÃ CHỌN");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel15.setText("CHƯA CHỌN");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));

        txt_Tenfilm.setEditable(false);
        txt_Tenfilm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_Tenfilm.setText("SPIDERMAN - NO WAY HOME");
        txt_Tenfilm.setFocusable(false);
        txt_Tenfilm.setOpaque(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Tenfilm, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Tenfilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        txt_ChoNgoi.setEditable(false);
        txt_ChoNgoi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_ChoNgoi.setText("CHỖ NGỒI:");
        txt_ChoNgoi.setFocusable(false);
        txt_ChoNgoi.setOpaque(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ChoNgoi)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        txt_ThoiGianChieu.setEditable(false);
        txt_ThoiGianChieu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_ThoiGianChieu.setText("GIỜ CHIẾU : 17:20 - 19:03");
        txt_ThoiGianChieu.setFocusable(false);
        txt_ThoiGianChieu.setOpaque(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ThoiGianChieu, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_ThoiGianChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        txt_TongTien.setEditable(false);
        txt_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_TongTien.setText("GIÁ GHẾ :  0 VNĐ");
        txt_TongTien.setFocusable(false);
        txt_TongTien.setOpaque(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_TongTien)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lbl_PhongChieu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_PhongChieu.setText("PHÒNG CHIẾU: PC001");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSButton217, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSButton220, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButton218, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButton219, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 195, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(168, 168, 168))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lbl_PhongChieu)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSButton218, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButton217, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSButton219, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(10, 10, 10)
                        .addComponent(rSButton220, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_PhongChieu)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_Cot, javax.swing.GroupLayout.PREFERRED_SIZE, 1585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(pnl_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(pnl_ShowGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 1487, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_Cot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(pnl_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_ShowGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File f = new File("");
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    QLGHENGOIDAO qlghengoidao = new QLGHENGOIDAO();
    QLPHONGCHIEUDAO qlphongchieudao = new QLPHONGCHIEUDAO();
    List<GHENGOI> listGheNgoi = null;
    PHONGCHIEU phongchieu = new PHONGCHIEU();
    List<LOAIGHE> listLoaiGhe = null;
    public static ChonChoNgoi Instance;
    public Double giave;
    public ArrayList<String> MaGhe = new ArrayList<>();
    public ArrayList<Double> GiaGhe = new ArrayList<>();

    private void init() {
        this.setIconImage(XImage.getAppIcon());
        designTextPane(txt_Tenfilm);
        designTextPane(txt_TongTien);
        designTextPane(txt_ThoiGianChieu);
        designTextPane(txt_ChoNgoi);
        Instance = this;
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }

    private void DrawForm(SUATCHIEU sc) {
        phongchieu = qlphongchieudao.selectebyID(sc.getMA_PHONG_CHIEU());
        listGheNgoi = qlghengoidao.SELECT_THEOPHONGCHIEU_SQL(sc.getMA_PHONG_CHIEU());
        listLoaiGhe = qlghengoidao.selectAllLoaiGhe();
        DecimalFormat formatter = new DecimalFormat("###,###,###");
        
        
        pnl_ShowGhe.removeAll();
        for (int i = 0; i < listGheNgoi.size(); i++) {
            RSButton button = new RSButton();
            if (listGheNgoi.get(i).isDA_CHON()) {
                button.setBackground(new Color(0, 0, 204));
                button.setColorHover(new Color(0, 0, 153));
            } else {
                if (listGheNgoi.get(i).getTEN_GHE().equalsIgnoreCase("THUONG")) {
                    button.setBackground(new Color(255, 0, 0));
                    button.setColorHover(new Color(255, 102, 102));
                } else if (listGheNgoi.get(i).getTEN_GHE().equalsIgnoreCase("VIP")) {
                    button.setBackground(new Color(255, 204, 0));
                    button.setColorHover(new Color(204, 204, 0));
                } else {
                    button.setBackground(new Color(0, 153, 0));
                    button.setColorHover(new Color(204, 204, 0));
                }
            }
            GHENGOI GHE = listGheNgoi.get(i);
            button.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    if (e.getClickCount() == 1 && !e.isConsumed()) {
                        if (MaGhe == null) {
                            MaGhe.add(GHE.getMA_GHE());
                            DatVe.Instance.MaGhe = MaGhe;
                            if (MaGhe != null) {
                                String ChoNgoi = "CHỖ NGỒI: ";
                                String ChoNgoiFormDatVe = "";
                                for (int j = 0; j < MaGhe.size(); j++) {
                                    if (j == 0) {
                                        ChoNgoi += MaGhe.get(j);
                                        ChoNgoiFormDatVe += MaGhe.get(j);
                                    } else {
                                        ChoNgoi += ", " + MaGhe.get(j);
                                        ChoNgoiFormDatVe += ", " + MaGhe.get(j);
                                    }
                                }
                                DatVe.Instance.txt.setText(ChoNgoiFormDatVe);
                                txt_ChoNgoi.setText(ChoNgoi);
                            }
                        } else {
                            if (MaGhe.size() < DatVe.Instance.sl.getValue().hashCode()) {
                                boolean isTrung = false;
                                for (String string : MaGhe) {
                                    if (GHE.getMA_GHE().equalsIgnoreCase(string)) {
                                        isTrung = true;
                                    }
                                }
                                if (!isTrung) {
                                    MaGhe.add(GHE.getMA_GHE());
                                    DatVe.Instance.MaGhe = MaGhe;

                                    if (MaGhe != null) {
                                        String ChoNgoi = "CHỖ NGỒI: ";
                                        String ChoNgoiFormDatVe = "";
                                        for (int j = 0; j < MaGhe.size(); j++) {
                                            if (j == 0) {
                                                ChoNgoi += MaGhe.get(j);
                                                ChoNgoiFormDatVe += MaGhe.get(j);
                                            } else {
                                                ChoNgoi += ", " + MaGhe.get(j);
                                                ChoNgoiFormDatVe += ", " + MaGhe.get(j);
                                            }
                                        }
                                        DatVe.Instance.txt.setText(ChoNgoiFormDatVe);
                                        txt_ChoNgoi.setText(ChoNgoi);
                                        for (LOAIGHE loaighe : listLoaiGhe) {
                                            if (GHE.getTEN_GHE().equalsIgnoreCase(loaighe.getTEN_GHE())) {
                                                GiaGhe.add(loaighe.getGIA());
                                            }
                                        }
                                        double TongTien = 0;
                                        if (GiaGhe != null) {
                                            if (GiaGhe.size() <= DatVe.Instance.sl.getValue().hashCode()) {
                                                for (Double double1 : GiaGhe) {
                                                    TongTien += double1;
                                                }
                                            } else {
                                                GiaGhe.remove(0);
                                                if (GiaGhe.size() <= DatVe.Instance.sl.getValue().hashCode()) {
                                                    for (Double double1 : GiaGhe) {
                                                        TongTien += double1;
                                                    }
                                                }
                                            }
                                        }
                                        txt_TongTien.setText("GIÁ GHẾ: " + formatter.format(TongTien) + " VNĐ");
                                        DatVe.Instance.giaGhe = TongTien;
                                        DatVe.Instance.tongtien();
                                    }
                                }
                            } else {
                                if (MaGhe != null) {
                                    MaGhe.remove(0);
                                    if (MaGhe.size() < DatVe.Instance.sl.getValue().hashCode()) {
                                        boolean isTrung = false;
                                        for (String string : MaGhe) {
                                            if (GHE.getMA_GHE().equalsIgnoreCase(string)) {
                                                isTrung = true;
                                            }
                                        }
                                        if (!isTrung) {
                                            MaGhe.add(GHE.getMA_GHE());
                                            DatVe.Instance.MaGhe = MaGhe;

                                            if (MaGhe != null) {
                                                String ChoNgoi = "CHỖ NGỒI: ";
                                                String ChoNgoiFormDatVe = "";
                                                for (int j = 0; j < MaGhe.size(); j++) {
                                                    if (j == 0) {
                                                        ChoNgoi += MaGhe.get(j);
                                                        ChoNgoiFormDatVe += MaGhe.get(j);
                                                    } else {
                                                        ChoNgoi += ", " + MaGhe.get(j);
                                                        ChoNgoiFormDatVe += ", " + MaGhe.get(j);
                                                    }
                                                }
                                                DatVe.Instance.txt.setText(ChoNgoiFormDatVe);
                                                txt_ChoNgoi.setText(ChoNgoi);
                                                for (LOAIGHE loaighe : listLoaiGhe) {
                                                    if (GHE.getTEN_GHE().equalsIgnoreCase(loaighe.getTEN_GHE())) {
                                                        GiaGhe.add(loaighe.getGIA());
                                                    }
                                                }
                                                double TongTien = 0;
                                                if (GiaGhe != null) {
                                                    if (GiaGhe.size() <= DatVe.Instance.sl.getValue().hashCode()) {
                                                        for (Double double1 : GiaGhe) {
                                                            TongTien += double1;
                                                        }
                                                    } else {
                                                        GiaGhe.remove(0);
                                                        if (GiaGhe.size() <= DatVe.Instance.sl.getValue().hashCode()) {
                                                            for (Double double1 : GiaGhe) {
                                                                TongTien += double1;
                                                            }
                                                        }
                                                    }
                                                }
                                                txt_TongTien.setText("GIÁ GHẾ: " + formatter.format(TongTien) + " VNĐ");
                                                DatVe.Instance.giaGhe = TongTien;
                                                DatVe.Instance.tongtien();
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        DatVe.Instance.listGiaGhe = GiaGhe;
                    }

                }
            });
            pnl_ShowGhe.add(button);
        }

        //set hình ghế + giá
        String duongdanGhe = f.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\loaighe\\";
        for (LOAIGHE loaighe : listLoaiGhe) {
            if (loaighe.getTEN_GHE().equalsIgnoreCase("THUONG")) {
                try {
                    lbl_GiaVeThuong.setText(formatter.format(loaighe.getGIA()) + " VNĐ");
                    lbl_HinhGheThuong.setIcon(XImage.ResizeImage(lbl_HinhGheThuong.getWidth(), lbl_HinhGheThuong.getHeight(), duongdanGhe + loaighe.getHINH()));
                } catch (Exception e) {
                }
            } else if (loaighe.getTEN_GHE().equalsIgnoreCase("VIP")) {
                try {
                    lbl_GiaVeVIP.setText(formatter.format(loaighe.getGIA()) + " VNĐ");
                    lbl_HinhGheVIP.setIcon(XImage.ResizeImage(lbl_HinhGheVIP.getWidth(), lbl_HinhGheVIP.getHeight(), duongdanGhe + loaighe.getHINH()));
                } catch (Exception e) {
                }
            } else {
                try {
                    lbl_HinhGheCouple.setText(formatter.format(loaighe.getGIA()) + " VNĐ");
                    lbl_HinhGheCouple.setIcon(XImage.ResizeImage(lbl_HinhGheCouple.getWidth(), lbl_HinhGheCouple.getHeight(), duongdanGhe + loaighe.getHINH()));
                } catch (Exception e) {
                }
            }
        }

    }

    public void fillToFormChonGhe(PHIM p, SUATCHIEU sc) {
        DrawForm(sc);
        txt_Tenfilm.setText(p.getTEN_PHIM());
        txt_ThoiGianChieu.setText("GIỜ CHIẾU: " + sc.getGIO_BAT_DAU() + " - " + sc.getGIO_KET_THUC());
        lbl_PhongChieu.setText("PHÒNG CHIẾU: " + sc.getMA_PHONG_CHIEU());
    }

    private void designTextPane(JTextPane txt) {
        txt.setOpaque(false);
        txt.setBorder(BorderFactory.createEmptyBorder());
        txt.setBackground(new Color(0, 0, 0, 0));

        StyledDocument style = txt.getStyledDocument();
        SimpleAttributeSet align = new SimpleAttributeSet();
        StyleConstants.setAlignment(align, StyleConstants.ALIGN_CENTER);
        style.setParagraphAttributes(0, style.getLength(), align, false);
    }
    
    public void clearform() {
        MaGhe = new ArrayList<>();
        GiaGhe = new ArrayList<>();
        txt_ChoNgoi.setText("CHỖ NGỒI: ");
        txt_TongTien.setText("GIÁ GHẾ: ");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChonChoNgoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChonChoNgoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChonChoNgoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChonChoNgoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChonChoNgoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_GiaVeCouple;
    private javax.swing.JLabel lbl_GiaVeThuong;
    private javax.swing.JLabel lbl_GiaVeVIP;
    private javax.swing.JLabel lbl_HinhGheCouple;
    private javax.swing.JLabel lbl_HinhGheThuong;
    private javax.swing.JLabel lbl_HinhGheVIP;
    private javax.swing.JLabel lbl_PhongChieu;
    private javax.swing.JPanel pnl_Cot;
    private javax.swing.JPanel pnl_Hang;
    private javax.swing.JPanel pnl_ShowGhe;
    private rojeru_san.RSButton rSButton217;
    private rojeru_san.RSButton rSButton218;
    private rojeru_san.RSButton rSButton219;
    private rojeru_san.RSButton rSButton220;
    private rojeru_san.RSButton rSButton221;
    private rojeru_san.RSButton rSButton222;
    private rojeru_san.RSButton rSButton223;
    private rojeru_san.RSButton rSButton224;
    private rojeru_san.RSButton rSButton225;
    private rojeru_san.RSButton rSButton226;
    private rojeru_san.RSButton rSButton227;
    private rojeru_san.RSButton rSButton228;
    private rojeru_san.RSButton rSButton229;
    private rojeru_san.RSButton rSButton230;
    private rojeru_san.RSButton rSButton231;
    private rojeru_san.RSButton rSButton232;
    private rojeru_san.RSButton rSButton248;
    private rojeru_san.RSButton rSButton249;
    private rojeru_san.RSButton rSButton250;
    private rojeru_san.RSButton rSButton251;
    private rojeru_san.RSButton rSButton252;
    private rojeru_san.RSButton rSButton253;
    private rojeru_san.RSButton rSButton254;
    private rojeru_san.RSButton rSButton255;
    private rojeru_san.RSButton rSButton256;
    private rojeru_san.RSButton rSButton257;
    private rojeru_san.RSButton rSButton258;
    private rojeru_san.RSButton rSButton259;
    private rojeru_san.RSButton rSButton260;
    private rojeru_san.RSButton rSButton261;
    private rojeru_san.RSButton rSButton262;
    private rojeru_san.RSButton rSButton263;
    private rojeru_san.RSButton rSButton264;
    private rojeru_san.RSButton rSButton265;
    private rojeru_san.RSButton rSButton266;
    private javax.swing.JTextPane txt_ChoNgoi;
    private javax.swing.JTextPane txt_Tenfilm;
    private javax.swing.JTextPane txt_ThoiGianChieu;
    private javax.swing.JTextPane txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
