/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;

import com.qlrp.dao.QLDADAO;
import com.qlrp.dao.QLKICHCOVALOAIDAO;
import com.qlrp.entity.DOAN;
import com.qlrp.entity.GIOHANG_DOAN;
import com.qlrp.entity.GIOHANG_PHIM;
import com.qlrp.entity.KICHCODA;
import com.qlrp.utils.XImage;
import com.qlrp.utils.getInfo;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.File;
import java.text.DecimalFormat;
import java.util.Iterator;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import rojeru_san.RSButton;
import rojerusan.RSTableMetro;

/**
 *
 * @author HAN-PC
 */
public class DatDoAn extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietDoAn
     */
    public DatDoAn() {
        initComponents();
        init();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_HinhDoAn = new javax.swing.JLabel();
        txt_TenDoAn = new javax.swing.JTextPane();
        pnl_KhoiChieu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_GiaDoAn = new javax.swing.JLabel();
        pnl_KhoiChieu1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbo_KichCo = new rojerusan.RSComboMetro();
        pnl_KhoiChieu2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sp_SoLuong = new javax.swing.JSpinner();
        pnl_KhoiChieu3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_TinhTrang = new javax.swing.JLabel();
        btn_ThemVaoGioHang = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/close.png"))); // NOI18N
        lbl_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HinhDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HinhDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txt_TenDoAn.setEditable(false);
        txt_TenDoAn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_TenDoAn.setText("BẮP RANG BƠ");
        txt_TenDoAn.setFocusable(false);
        txt_TenDoAn.setOpaque(false);

        pnl_KhoiChieu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("GIÁ:");

        lbl_GiaDoAn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_GiaDoAn.setText("35.000 VNĐ");

        javax.swing.GroupLayout pnl_KhoiChieuLayout = new javax.swing.GroupLayout(pnl_KhoiChieu);
        pnl_KhoiChieu.setLayout(pnl_KhoiChieuLayout);
        pnl_KhoiChieuLayout.setHorizontalGroup(
            pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieuLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_GiaDoAn))
        );
        pnl_KhoiChieuLayout.setVerticalGroup(
            pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieuLayout.createSequentialGroup()
                .addGroup(pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_GiaDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pnl_KhoiChieu1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("KÍCH CỠ:");

        cbo_KichCo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnl_KhoiChieu1Layout = new javax.swing.GroupLayout(pnl_KhoiChieu1);
        pnl_KhoiChieu1.setLayout(pnl_KhoiChieu1Layout);
        pnl_KhoiChieu1Layout.setHorizontalGroup(
            pnl_KhoiChieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(cbo_KichCo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_KhoiChieu1Layout.setVerticalGroup(
            pnl_KhoiChieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbo_KichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_KhoiChieu2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("SỐ LƯỢNG:");

        sp_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sp_SoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        sp_SoLuong.setPreferredSize(new java.awt.Dimension(7, 20));
        sp_SoLuong.setRequestFocusEnabled(false);
        sp_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sp_SoLuongKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnl_KhoiChieu2Layout = new javax.swing.GroupLayout(pnl_KhoiChieu2);
        pnl_KhoiChieu2.setLayout(pnl_KhoiChieu2Layout);
        pnl_KhoiChieu2Layout.setHorizontalGroup(
            pnl_KhoiChieu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(sp_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_KhoiChieu2Layout.setVerticalGroup(
            pnl_KhoiChieu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu2Layout.createSequentialGroup()
                .addGroup(pnl_KhoiChieu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_KhoiChieu2Layout.createSequentialGroup()
                        .addComponent(sp_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_KhoiChieu2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnl_KhoiChieu3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("TÌNH TRẠNG:");

        lbl_TinhTrang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TinhTrang.setText("CÒN HÀNG");

        javax.swing.GroupLayout pnl_KhoiChieu3Layout = new javax.swing.GroupLayout(pnl_KhoiChieu3);
        pnl_KhoiChieu3.setLayout(pnl_KhoiChieu3Layout);
        pnl_KhoiChieu3Layout.setHorizontalGroup(
            pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lbl_TinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );
        pnl_KhoiChieu3Layout.setVerticalGroup(
            pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_ThemVaoGioHang.setText("THÊM VÀO GIỎ HÀNG");
        btn_ThemVaoGioHang.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btn_ThemVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemVaoGioHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(807, Short.MAX_VALUE)
                        .addComponent(lbl_Exit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pnl_KhoiChieu2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl_KhoiChieu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(pnl_KhoiChieu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_TenDoAn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(pnl_KhoiChieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(btn_ThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Exit)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_TenDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_KhoiChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnl_KhoiChieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(pnl_KhoiChieu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnl_KhoiChieu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 847, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File f = new File("");
    DOAN doan = new DOAN();
    DefaultTableModel model;
    DecimalFormat formatter = new DecimalFormat("###,###,###");

    public static DatDoAn Instance;
    List<DOAN> listda = null;
    List<KICHCODA> listKCDA = null;
    QLDADAO qldadao = new QLDADAO();
    QLKICHCOVALOAIDAO qlkichcovaloaidao = new QLKICHCOVALOAIDAO();

    String duongdanBanner = f.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\PHIM\\POSTER\\";

    private void init() {
        this.setIconImage(XImage.getAppIcon());
        designTextPane(txt_TenDoAn);
        Instance = this;
        sp_SoLuong.setValue(1);
        addEventSoLuong();
    }

    private void designTextPane(JTextPane txt) {
        txt.setOpaque(false);
        txt.setBorder(BorderFactory.createEmptyBorder());
        txt.setBackground(new Color(0, 0, 0, 0));

        StyledDocument style = txt.getStyledDocument();
        SimpleAttributeSet align = new SimpleAttributeSet();
        StyleConstants.setAlignment(align, StyleConstants.ALIGN_CENTER);
        style.setParagraphAttributes(0, style.getLength(), align, false);
    }

    private void fillToComboboxKichCo() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_KichCo.getModel();
        cbo_KichCo.removeAllItems();
        model.addElement("KÍCH CỠ");
        listKCDA = qlkichcovaloaidao.selectAllKichCo();
        for (KICHCODA kc : listKCDA) {
            model.addElement(kc.getTEN_KICH_CO_DA());
        }
    }

    public void fillToChiTietDoAn(DOAN food) {
        doan = food;
        txt_TenDoAn.setText(food.getTENDOAN().toUpperCase());
        lbl_GiaDoAn.setText(formatter.format(food.getDONGIA()) + " VNĐ");
        if (food.getSOLUONG() == 0) {
            lbl_TinhTrang.setText("HẾT HÀNG");
            lbl_TinhTrang.setForeground(Color.RED);
        } else {
            lbl_TinhTrang.setText("CÒN " + food.getSOLUONG() + " MÓN");
            lbl_TinhTrang.setForeground(Color.BLACK);
        }

        fillToComboboxKichCo();

        try {

            lbl_HinhDoAn.setIcon(XImage.ResizeImage(lbl_HinhDoAn.getWidth(), lbl_HinhDoAn.getHeight(), duongdanBanner + food.getHINH()));
            System.out.println(duongdanBanner + food.getHINH());
        } catch (Exception e) {
        }
    }
    RSButton button = new RSButton();

    private void fillToCart(RSTableMetro table) {
        model = (DefaultTableModel) table.getModel();
        double tt = 0; 
        model.setRowCount(0);

        for (GIOHANG_PHIM giohang_phim : getInfo.listSP_PHIM) {
            model.addRow(new Object[]{giohang_phim.getPOSTER(), giohang_phim.getTEN_SAN_PHAM(), giohang_phim.getSO_LUONG(), formatter.format(giohang_phim.getGIA()) + " VNĐ", "X"});
            tt += giohang_phim.getGIA();
        }
        table.getColumnModel().getColumn(0).setCellRenderer(new DatDoAn.ImageRendererMovie());
//        table.getColumnModel().getColumn(4).setCellRenderer(new DatDoAn.ButtonRenderer());
//        table.getColumnModel().getColumn(4).setCellEditor(new DatDoAn.ButtonEditor(new JCheckBox()));

        for (GIOHANG_DOAN giohang_doan : getInfo.listSP_DOAN) {
            model.addRow(new Object[]{giohang_doan.getHINH(), giohang_doan.getTEN_SAN_PHAM(), giohang_doan.getSO_LUONG() + " - " + giohang_doan.getKICH_CO(), formatter.format(giohang_doan.getGIA()) + " VNĐ", "X"});
            tt += giohang_doan.getGIA();
        }
        table.getColumnModel().getColumn(0).setCellRenderer(new DatDoAn.ImageRendererFood());
//        table.getColumnModel().getColumn(4).setCellRenderer(new DatDoAn.ButtonRenderer());
//        table.getColumnModel().getColumn(4).setCellEditor(new DatDoAn.ButtonEditor(new JCheckBox()));
        table.getColumnModel().getColumn(4).setCellRenderer(r);
        
        KHHOME.Instance.sl.setText((getInfo.listSP_PHIM.size() + getInfo.listSP_DOAN.size()) + "");
        KHHOME.Instance.lbl.setText(formatter.format(tt) + " VNĐ");
    }

    DefaultTableCellRenderer r = new DefaultTableCellRenderer() {
        Font font = new Font("Segoe UI", Font.BOLD, 32);

        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus,
                    row, column);
            setOpaque(true);
            setFont(font);
            setHorizontalAlignment(RSButton.CENTER);
            setBackground(Color.WHITE);
            setForeground(Color.BLACK);
            return this;
        }

    };

    private class ImageRendererMovie extends DefaultTableCellRenderer {

        //add img into table
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            String photoname = String.valueOf(value);
            ImageIcon ImageIcon = new ImageIcon(
                    new ImageIcon("src/main/resources/com/qlrp/image/PHIM/POSTER/" + photoname).
                            getImage().getScaledInstance(70, 100, Image.SCALE_SMOOTH));
            //add border for img
            JLabel lb = new JLabel(ImageIcon);
            return lb;
        }
    }

    private class ImageRendererFood extends DefaultTableCellRenderer {

        //add img into table
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            String photoname = String.valueOf(value);
            ImageIcon ImageIcon = new ImageIcon(
                    new ImageIcon("src/main/resources/com/qlrp/image/PHIM/POSTER/" + photoname).
                            getImage().getScaledInstance(70, 100, Image.SCALE_SMOOTH));
            //add border for img
            JLabel lb = new JLabel(ImageIcon);
            return lb;
        }
    }

    private class ButtonRenderer extends RSButton implements TableCellRenderer {

        //CONSTRUCTOR
        public ButtonRenderer() {
            //SET BUTTON PROPERTIES
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object obj,
                boolean selected, boolean focused, int row, int col) {

            //SET PASSED OBJECT AS BUTTON TEXT
            setText((obj == null) ? "" : obj.toString());

            return this;
        }

    }

    private class ButtonEditor extends DefaultCellEditor {

        protected RSButton btn;
        private String lbl;

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            btn = new RSButton();
            btn.setBackground(new Color(255, 255, 255));
            btn.setOpaque(true);
            String url = f.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\icon\\close_70px.png";
            btn.setIcon(XImage.ResizeImage(32, 32, url));

            //WHEN BUTTON IS CLICKED
            btn.addActionListener((ActionEvent e) -> {

            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int row, int column) {
            lbl = (value == null) ? "" : value.toString();
            btn.setText(lbl);
            return btn;
        }

        @Override
        public Object getCellEditorValue() {
            return lbl;
        }
    }

    private void lbl_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_lbl_ExitMouseClicked

    boolean isThemVaoGioHang = false;

    private void sp_SoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sp_SoLuongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sp_SoLuongKeyReleased

    private void addToListSP() {
        GIOHANG_DOAN giohang_DA = new GIOHANG_DOAN();
        giohang_DA.setGIA(doan.getDONGIA() * sp_SoLuong.getValue().hashCode());
        giohang_DA.setSO_LUONG(sp_SoLuong.getValue().hashCode());
        giohang_DA.setKICH_CO(cbo_KichCo.getSelectedItem().toString());
        giohang_DA.setTEN_SAN_PHAM(doan.getTENDOAN());
        giohang_DA.setHINH(doan.getHINH());

        List<GIOHANG_DOAN> list = getInfo.listSP_DOAN;
        list.add(giohang_DA);
        getInfo.listSP_DOAN = list;
    }

    private boolean validateForm() {
        String loi = "";

        if (qldadao.selectebyID(doan.getTENDOAN()) != null) {
            doan = qldadao.selectebyID(doan.getTENDOAN());
            if (doan.getSOLUONG() == 0) {
                loi += "SẢN PHẨM ĐÃ HẾT HÀNG! \n";
                sp_SoLuong.setValue(0);
                fillToChiTietDoAn(doan);
            } else if (sp_SoLuong.getValue().hashCode() > doan.getSOLUONG()) {
                loi += "SỐ LƯỢNG ĐÃ VƯỢT QUÁ SỐ SẢN PHẨM CÒN LẠI! \n";
                sp_SoLuong.setValue(doan.getSOLUONG());
                tongtien();
            } else if (sp_SoLuong.getValue().hashCode() <= 0) {
                loi += "SỐ LƯỢNG PHẢI LỚN HƠN 0! \n";
                sp_SoLuong.setValue(1);
                tongtien();
            }

            if (doan.getSOLUONG() != 0 && cbo_KichCo.getSelectedIndex() == 0) {
                loi += "VUI LÒNG CHỌN KÍCH CỠ! \n";
            }

        }

        if (!loi.equals("")) {
            JOptionPane.showMessageDialog(this, loi, "LỖI", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void tongtien() {
        lbl_GiaDoAn.setText(formatter.format(sp_SoLuong.getValue().hashCode() * doan.getDONGIA()) + " VNĐ");
    }

    private void addEventSoLuong() {
        sp_SoLuong.addChangeListener((ChangeEvent e) -> {
            tongtien();
        });
    }

    private void btn_ThemVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemVaoGioHangActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            try {
                qldadao.updateSL(doan.getSOLUONG() - sp_SoLuong.getValue().hashCode(), doan.getTENDOAN());
                addToListSP();
                fillToCart(KHHOME.Instance.table);
                JOptionPane.showMessageDialog(this, "THÊM THÀNH CÔNG!", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_btn_ThemVaoGioHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatDoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatDoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatDoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatDoAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatDoAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_ThemVaoGioHang;
    private rojerusan.RSComboMetro cbo_KichCo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Exit;
    private javax.swing.JLabel lbl_GiaDoAn;
    private javax.swing.JLabel lbl_HinhDoAn;
    private javax.swing.JLabel lbl_TinhTrang;
    private javax.swing.JPanel pnl_KhoiChieu;
    private javax.swing.JPanel pnl_KhoiChieu1;
    private javax.swing.JPanel pnl_KhoiChieu2;
    private javax.swing.JPanel pnl_KhoiChieu3;
    private javax.swing.JSpinner sp_SoLuong;
    private javax.swing.JTextPane txt_TenDoAn;
    // End of variables declaration//GEN-END:variables
}
