/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;

import com.qlrp.dao.QLGHENGOIDAO;
import com.qlrp.dao.QLSUATCHIEUDAO;
import com.qlrp.dao.QLGIAVEDAO;
import com.qlrp.dao.QLVEDATDAO;
import com.qlrp.entity.GHENGOI;
import com.qlrp.entity.GIAVE;
import com.qlrp.entity.GIOHANG_DOAN;
import com.qlrp.entity.GIOHANG_PHIM;
import com.qlrp.entity.PHIM;
import com.qlrp.entity.SUATCHIEU;
import com.qlrp.entity.VEDAT;
import com.qlrp.utils.Auth;
import com.qlrp.utils.XImage;
import com.qlrp.utils.getInfo;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.Time;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import rojeru_san.RSButton;
import rojerusan.RSTableMetro;

/**
 *
 * @author HAN-PC
 */
public class DatVe extends javax.swing.JFrame {

    /**
     * Creates new form DatVe
     */
    public DatVe() {
        initComponents();
        init();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_ThemVaoGioHang = new rojerusan.RSMaterialButtonRectangle();
        pnl_KhoiChieu2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sp_SoLuong = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        lbl_HinhFilm = new javax.swing.JLabel();
        pnl_KhoiChieu3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_GheNgoi = new javax.swing.JTextPane();
        txt_Tenfilm = new javax.swing.JTextPane();
        pnl_KhoiChieu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_GiaVe = new javax.swing.JLabel();
        pnl_KhoiChieu1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_MaVe = new javax.swing.JLabel();
        pnl_KhoiChieu5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbo_PhongChieu = new rojerusan.RSComboMetro();
        pnl_KhoiChieu6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbl_DinhDangPhim = new javax.swing.JLabel();
        pnl_KhoiChieu7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbo_GioChieu = new rojerusan.RSComboMetro();
        pnl_KhoiChieu8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbo_NgayChieu = new rojerusan.RSComboMetro();
        btn_ChonGheNgoi = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ĐẶT VÉ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_ThemVaoGioHang.setText("THÊM VÀO GIỎ HÀNG");
        btn_ThemVaoGioHang.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btn_ThemVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemVaoGioHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_ThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btn_ThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnl_KhoiChieu2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("SỐ LƯỢNG:");

        sp_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sp_SoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        sp_SoLuong.setPreferredSize(new java.awt.Dimension(7, 20));
        sp_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sp_SoLuongKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnl_KhoiChieu2Layout = new javax.swing.GroupLayout(pnl_KhoiChieu2);
        pnl_KhoiChieu2.setLayout(pnl_KhoiChieu2Layout);
        pnl_KhoiChieu2Layout.setHorizontalGroup(
            pnl_KhoiChieu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sp_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_KhoiChieu2Layout.setVerticalGroup(
            pnl_KhoiChieu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu2Layout.createSequentialGroup()
                .addComponent(sp_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_KhoiChieu2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbl_HinhFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbl_HinhFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_KhoiChieu3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("GHẾ NGỒI:");

        txt_GheNgoi.setEditable(false);
        txt_GheNgoi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_GheNgoi.setText("A1");
        txt_GheNgoi.setFocusable(false);
        txt_GheNgoi.setOpaque(false);

        javax.swing.GroupLayout pnl_KhoiChieu3Layout = new javax.swing.GroupLayout(pnl_KhoiChieu3);
        pnl_KhoiChieu3.setLayout(pnl_KhoiChieu3Layout);
        pnl_KhoiChieu3Layout.setHorizontalGroup(
            pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(txt_GheNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_KhoiChieu3Layout.setVerticalGroup(
            pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pnl_KhoiChieu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txt_GheNgoi))
                .addGap(2, 2, 2))
        );

        txt_Tenfilm.setEditable(false);
        txt_Tenfilm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_Tenfilm.setText("DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS");
        txt_Tenfilm.setFocusable(false);
        txt_Tenfilm.setOpaque(false);

        pnl_KhoiChieu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("GIÁ VÉ:");

        lbl_GiaVe.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_GiaVe.setForeground(new java.awt.Color(204, 0, 0));
        lbl_GiaVe.setText("35,000 VNĐ");

        javax.swing.GroupLayout pnl_KhoiChieuLayout = new javax.swing.GroupLayout(pnl_KhoiChieu);
        pnl_KhoiChieu.setLayout(pnl_KhoiChieuLayout);
        pnl_KhoiChieuLayout.setHorizontalGroup(
            pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieuLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(112, 112, 112)
                .addComponent(lbl_GiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_KhoiChieuLayout.setVerticalGroup(
            pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieuLayout.createSequentialGroup()
                .addGroup(pnl_KhoiChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_GiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pnl_KhoiChieu1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("MÃ VÉ:");

        lbl_MaVe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_MaVe.setText("V001");

        javax.swing.GroupLayout pnl_KhoiChieu1Layout = new javax.swing.GroupLayout(pnl_KhoiChieu1);
        pnl_KhoiChieu1.setLayout(pnl_KhoiChieu1Layout);
        pnl_KhoiChieu1Layout.setHorizontalGroup(
            pnl_KhoiChieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(lbl_MaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_KhoiChieu1Layout.setVerticalGroup(
            pnl_KhoiChieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu1Layout.createSequentialGroup()
                .addGroup(pnl_KhoiChieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnl_KhoiChieu5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("PHÒNG CHIẾU:");

        cbo_PhongChieu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PHÒNG CHIẾU", "PC001" }));
        cbo_PhongChieu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout pnl_KhoiChieu5Layout = new javax.swing.GroupLayout(pnl_KhoiChieu5);
        pnl_KhoiChieu5.setLayout(pnl_KhoiChieu5Layout);
        pnl_KhoiChieu5Layout.setHorizontalGroup(
            pnl_KhoiChieu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(48, 48, 48)
                .addComponent(cbo_PhongChieu, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
        );
        pnl_KhoiChieu5Layout.setVerticalGroup(
            pnl_KhoiChieu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu5Layout.createSequentialGroup()
                .addGroup(pnl_KhoiChieu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_PhongChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pnl_KhoiChieu6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("ĐỊNH DẠNG PHIM:");

        lbl_DinhDangPhim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_DinhDangPhim.setText("3D");

        javax.swing.GroupLayout pnl_KhoiChieu6Layout = new javax.swing.GroupLayout(pnl_KhoiChieu6);
        pnl_KhoiChieu6.setLayout(pnl_KhoiChieu6Layout);
        pnl_KhoiChieu6Layout.setHorizontalGroup(
            pnl_KhoiChieu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_DinhDangPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_KhoiChieu6Layout.setVerticalGroup(
            pnl_KhoiChieu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu6Layout.createSequentialGroup()
                .addGroup(pnl_KhoiChieu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_DinhDangPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pnl_KhoiChieu7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("GIỜ CHIẾU:");

        cbo_GioChieu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout pnl_KhoiChieu7Layout = new javax.swing.GroupLayout(pnl_KhoiChieu7);
        pnl_KhoiChieu7.setLayout(pnl_KhoiChieu7Layout);
        pnl_KhoiChieu7Layout.setHorizontalGroup(
            pnl_KhoiChieu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu7Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(81, 81, 81)
                .addComponent(cbo_GioChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_KhoiChieu7Layout.setVerticalGroup(
            pnl_KhoiChieu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu7Layout.createSequentialGroup()
                .addGroup(pnl_KhoiChieu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_KhoiChieu7Layout.createSequentialGroup()
                        .addComponent(cbo_GioChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_KhoiChieu7Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );

        pnl_KhoiChieu8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("NGÀY CHIẾU:");

        cbo_NgayChieu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NGÀY CHIẾU", "2021-12-14" }));
        cbo_NgayChieu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout pnl_KhoiChieu8Layout = new javax.swing.GroupLayout(pnl_KhoiChieu8);
        pnl_KhoiChieu8.setLayout(pnl_KhoiChieu8Layout);
        pnl_KhoiChieu8Layout.setHorizontalGroup(
            pnl_KhoiChieu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu8Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_KhoiChieu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_KhoiChieu8Layout.createSequentialGroup()
                    .addGap(0, 178, Short.MAX_VALUE)
                    .addComponent(cbo_NgayChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnl_KhoiChieu8Layout.setVerticalGroup(
            pnl_KhoiChieu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_KhoiChieu8Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_KhoiChieu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_KhoiChieu8Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(cbo_NgayChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btn_ChonGheNgoi.setText("CHỌN GHẾ");
        btn_ChonGheNgoi.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btn_ChonGheNgoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonGheNgoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(txt_Tenfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pnl_KhoiChieu6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnl_KhoiChieu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_ChonGheNgoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnl_KhoiChieu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_KhoiChieu7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_KhoiChieu8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnl_KhoiChieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_KhoiChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_KhoiChieu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_Tenfilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_KhoiChieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_KhoiChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pnl_KhoiChieu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_KhoiChieu8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_KhoiChieu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_KhoiChieu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_KhoiChieu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_KhoiChieu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_ChonGheNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static DatVe Instance;
    public JLabel lblvitri;
    public double giaGhe = 0;
    public ArrayList<String> MaGhe = new ArrayList<>();
    public ArrayList<Double> listGiaGhe = new ArrayList<>();
    public JSpinner sl;
    public JTextPane txt;

    File f = new File("");
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    ChonChoNgoi ccn = new ChonChoNgoi();
    DefaultTableModel model;

    QLSUATCHIEUDAO qlsuatchieudao = new QLSUATCHIEUDAO();
    QLGIAVEDAO qlvedao = new QLGIAVEDAO();
    QLVEDATDAO qlvedatdao = new QLVEDATDAO();
    QLGHENGOIDAO qlghengoidao = new QLGHENGOIDAO();

    SUATCHIEU suatchieu = new SUATCHIEU();
    PHIM phim = new PHIM();
    VEDAT vedat = new VEDAT();
    List<GIAVE> listGiaVe = null;
    List<SUATCHIEU> listSuatChieu = null;
    List<SUATCHIEU> listGioChieu = null;
    double giave = 0;

    private void init() {
        this.setIconImage(XImage.getAppIcon());
        designTextPane(txt_Tenfilm);
        Instance = this;
        sl = sp_SoLuong;
        txt = txt_GheNgoi;
        SetVisible();
        addEventComboBox();
        addEventSoLuong();
        tongtien();
    }

    private void designTextPane(JTextPane txt) {
        txt.setOpaque(false);
        txt.setBorder(BorderFactory.createEmptyBorder());
        txt.setBackground(new Color(0, 0, 0, 0));

        StyledDocument style = txt.getStyledDocument();
        SimpleAttributeSet align = new SimpleAttributeSet();
        StyleConstants.setAlignment(align, StyleConstants.ALIGN_CENTER);
        style.setParagraphAttributes(0, style.getLength(), align, false);
    }

    public void fillToFormDatVe(PHIM p) {
        phim = p;
        listGiaVe = qlvedao.selectAllGiaVe();
        try {
            String duongdanPoster = f.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\PHIM\\POSTER\\";
            lbl_HinhFilm.setIcon(XImage.ResizeImage(lbl_HinhFilm.getWidth(), lbl_HinhFilm.getHeight(), duongdanPoster + p.getPOSTER()));
        } catch (Exception e) {
        }

        txt_Tenfilm.setText(p.getTEN_PHIM());

        for (GIAVE gv : listGiaVe) {
            if (gv.getLOAI_VE().equalsIgnoreCase("Vé Thường")) {
                giave = gv.getDON_GIA();
            }
        }

        autoCreateMaVe();
        fillToComBoBoxNgayChieu(p);
    }

    private void autoCreateMaVe() {
        String manv;
        while (true) {
            Random rand = new Random();
            int ranNum = rand.nextInt(100000) + 1;
            manv = "VD" + ranNum;
            if (qlvedatdao.selectebyID(manv) == null) {
                break;
            }
        }
        lbl_MaVe.setText(manv);
    }

    private void addEventComboBox() {
        cbo_NgayChieu.addItemListener((ItemEvent e) -> {
            if (e.getID() == ItemEvent.ITEM_STATE_CHANGED) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    if (cbo_NgayChieu.getSelectedIndex() != 0) {
                        cbo_GioChieu.setVisible(true);
                        Date GioChieu = (Date) cbo_NgayChieu.getSelectedItem();
                        fillToComBoBoxGioChieu(GioChieu);
                    } else {
                        SetVisible();
                    }

                }
            }
        });

        cbo_GioChieu.addItemListener((ItemEvent e) -> {
            if (e.getID() == ItemEvent.ITEM_STATE_CHANGED) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    if (cbo_GioChieu.getSelectedIndex() != 0) {
                        cbo_PhongChieu.setVisible(true);
                        Date NgayChieu = (Date) cbo_NgayChieu.getSelectedItem();
                        String gioChieu = (String) cbo_GioChieu.getSelectedItem();
                        String gioBatDau = gioChieu.substring(0, gioChieu.lastIndexOf("-") - 1);
                        String gioKetThuc = gioChieu.substring(gioChieu.lastIndexOf("-") + 2);
                        fillToComBoBoxPhongChieu(NgayChieu, gioBatDau, gioKetThuc);
                    } else {
                        cbo_PhongChieu.setVisible(false);
                        btn_ChonGheNgoi.setVisible(false);
                        lbl_DinhDangPhim.setText("");
                        txt_GheNgoi.setText("");
                        btn_ThemVaoGioHang.setEnabled(false);
                    }
                }
            }
        });

        cbo_PhongChieu.addItemListener((ItemEvent e) -> {
            if (e.getID() == ItemEvent.ITEM_STATE_CHANGED) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    if (cbo_PhongChieu.getSelectedIndex() != 0) {
                        String PC = (String) cbo_PhongChieu.getSelectedItem();
                        Date NgayChieu = (Date) cbo_NgayChieu.getSelectedItem();
                        String gioChieu = (String) cbo_GioChieu.getSelectedItem();
                        Time gioBatDau = Time.valueOf(gioChieu.substring(0, gioChieu.lastIndexOf("-") - 1));
                        Time gioKetThuc = Time.valueOf(gioChieu.substring(gioChieu.lastIndexOf("-") + 2));
                        for (SUATCHIEU suatchieu1 : listSuatChieu) {
                            if ((suatchieu1.getNGAY_CHIEU().compareTo(NgayChieu) == 0) && (suatchieu1.getGIO_BAT_DAU().compareTo(gioBatDau) == 0)
                                    && (suatchieu1.getGIO_KET_THUC().compareTo(gioKetThuc) == 0) && suatchieu1.getMA_PHONG_CHIEU().equalsIgnoreCase(PC)) {
                                lbl_DinhDangPhim.setText(suatchieu1.getTEN_DINH_DANG_PHIM());
                                btn_ChonGheNgoi.setVisible(true);
                                btn_ThemVaoGioHang.setEnabled(true);
                                suatchieu = listSuatChieu.get(0);
                                ChonChoNgoi.Instance.lbl_PC.setText("PHÒNG CHIẾU: " + cbo_PhongChieu.getSelectedItem());
                            }
                        }
                    } else {
                        btn_ChonGheNgoi.setVisible(false);
                        lbl_DinhDangPhim.setText("");
                        txt_GheNgoi.setText("");
                        btn_ThemVaoGioHang.setEnabled(false);
                    }
                }
            }
        });
    }

    private void fillToComBoBoxNgayChieu(PHIM p) {
        try {
            listSuatChieu = qlsuatchieudao.selectebyMaPhim(p.getMA_PHIM());
            DefaultComboBoxModel modelNgayChieu = (DefaultComboBoxModel) cbo_NgayChieu.getModel();
            cbo_NgayChieu.removeAllItems();
            modelNgayChieu.addElement("NGÀY CHIẾU");
            for (SUATCHIEU suatchieu1 : listSuatChieu) {
                modelNgayChieu.addElement(suatchieu1.getNGAY_CHIEU());
                suatchieu = suatchieu1;
            }
        } catch (Exception e) {

        }

    }

    private void fillToComBoBoxGioChieu(Date NgayChieu) {
        try {
            listSuatChieu = qlsuatchieudao.selectebyGioChieu(phim.getMA_PHIM(), String.valueOf(NgayChieu));
            DefaultComboBoxModel modelGioChieu = (DefaultComboBoxModel) cbo_GioChieu.getModel();
            cbo_GioChieu.removeAllItems();
            modelGioChieu.addElement("GIỜ CHIẾU");
            for (SUATCHIEU suatchieu1 : listSuatChieu) {
                modelGioChieu.addElement(suatchieu1.getGIO_BAT_DAU() + " - " + suatchieu1.getGIO_KET_THUC());
            }
        } catch (Exception e) {
        }

    }

    private void fillToComBoBoxPhongChieu(Date NgayChieu, String gioBatDau, String gioKetThuc) {
        try {
            listSuatChieu = qlsuatchieudao.selectebyPhongChieu(phim.getMA_PHIM(), String.valueOf(NgayChieu), gioBatDau, gioKetThuc);
            DefaultComboBoxModel modelPhongChieu = (DefaultComboBoxModel) cbo_PhongChieu.getModel();
            cbo_PhongChieu.removeAllItems();
            modelPhongChieu.addElement("PHÒNG CHIẾU");
            for (SUATCHIEU suatchieu1 : listSuatChieu) {
                modelPhongChieu.addElement(suatchieu1.getMA_PHONG_CHIEU());
                suatchieu = suatchieu1;
            }
        } catch (Exception e) {
        }

    }

    public void SetVisible() {
        cbo_GioChieu.setVisible(false);
        cbo_PhongChieu.setVisible(false);
        btn_ChonGheNgoi.setVisible(false);
        lbl_DinhDangPhim.setText("");
        txt_GheNgoi.setText("");
        btn_ThemVaoGioHang.setEnabled(false);
    }

    private boolean validateForm() {
        String loi = "";
        String testGhe = "";

        if (sp_SoLuong.getValue().hashCode() < 1) {
            sp_SoLuong.setValue(1);
            sp_SoLuong.setFocusable(true);
            loi += "SỐ LƯỢNG PHẢI LỚN HƠN 0! \n";
        } else {
            if (txt_GheNgoi.getText().equals("") || txt_GheNgoi.getText() == null || MaGhe.size() < sp_SoLuong.getValue().hashCode()) {
                loi += "BẠN PHẢI CHỌN ĐỦ SỐ GHẾ! \n";
            } else if (MaGhe.size() > sp_SoLuong.getValue().hashCode()) {
                loi += "BẠN ÐÃ CHỌN DƯ GHẾ VUI LÒNG CHỌN LẠI! \n";
                listGiaGhe = null;
                MaGhe = null;
                giaGhe = 0;
                tongtien();
                txt_GheNgoi.setText("");
            } else {
                List<GHENGOI> listghengoi = new ArrayList<>();
                String maPC = cbo_PhongChieu.getSelectedItem() + "";
                for (String mg : MaGhe) {
                    listghengoi.add(qlghengoidao.selecteGhe_Ngoi(maPC, mg));
                }
                if (!listghengoi.isEmpty()) {
                    for (GHENGOI ghengoi : listghengoi) {
                        if (ghengoi.isDA_CHON()) {
                            testGhe += ghengoi.getMA_GHE() + " ";
                        }
                    }

                }

                if (!testGhe.equals("")) {
                    loi += "GHẾ " + testGhe + "ĐÃ ĐƯỢC CHỌN \n";
                }

            }
        }

        if (!loi.equals("")) {
            JOptionPane.showMessageDialog(this, loi, "LỖI", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void addEventSoLuong() {
        sp_SoLuong.addChangeListener((ChangeEvent e) -> {
            if (sp_SoLuong.getValue().hashCode() > 0) {
                btn_ChonGheNgoi.setEnabled(true);
                if (MaGhe != null && (MaGhe.size() > sp_SoLuong.getValue().hashCode()) && listGiaGhe != null) {
                    giaGhe = giaGhe - listGiaGhe.get(listGiaGhe.size() - 1);
                    MaGhe.remove(MaGhe.size() - 1);
                    listGiaGhe.remove(listGiaGhe.size() - 1);
                    tongtien();
                    String ghe = "";
                    for (int i = 0; i < MaGhe.size(); i++) {
                        if (i == 0) {
                            ghe += MaGhe.get(i);
                        } else {
                            ghe += ", " + MaGhe.get(i);
                        }
                    }
                    txt_GheNgoi.setText(ghe);

                }
            } else {
                validateForm();
                sp_SoLuong.setValue(1);
            }
            tongtien();
        });
    }
    double tongtien = 0;

    public void tongtien() {
        double tt = (giave * sp_SoLuong.getValue().hashCode()) + giaGhe;
        tongtien = tt;
        lbl_GiaVe.setText(formatter.format(tt) + " VNĐ");
    }

    public void clearForm() {
        MaGhe = null;
        listGiaGhe = null;
        giaGhe = 0;
        sp_SoLuong.setValue(1);
        txt_GheNgoi.setText("");
        lbl_DinhDangPhim.setText("");
        lbl_GiaVe.setText(0 + " VNĐ");
        tongtien();
    }

    private void btn_ChonGheNgoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonGheNgoiActionPerformed
        // TODO add your handling code here:
        if (sp_SoLuong.getValue().hashCode() > 0) {
            listGiaVe = qlvedao.selectAllGiaVe();
            if (ccn.isVisible()) {
                ccn.setVisible(false);
                ccn.setVisible(true);
                ccn.fillToFormChonGhe(phim, suatchieu, MaGhe);
                if (listGiaGhe == null && MaGhe == null) {
                    ccn.clearform();
                }
                for (GIAVE giave : listGiaVe) {
                    if (giave.getLOAI_VE().equalsIgnoreCase("Vé Thường")) {
                        ChonChoNgoi.Instance.giave = giave.getDON_GIA();
                    }
                }

            } else {
                ccn.setVisible(true);
                ccn.fillToFormChonGhe(phim, suatchieu, MaGhe);
                if (listGiaGhe == null && MaGhe == null) {
                    ccn.clearform();
                }
                for (GIAVE giave : listGiaVe) {
                    if (giave.getLOAI_VE().equalsIgnoreCase("Vé Thường")) {
                        ChonChoNgoi.Instance.giave = giave.getDON_GIA();
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "SỐ LƯỢNG PHẢI LỚN HƠN 0!", "LỖI", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ChonGheNgoiActionPerformed

    RSButton button = new RSButton();

    private void fillToCart(RSTableMetro table) {
        List<GIOHANG_DOAN> listDoAn = getInfo.listSP_DOAN;
        List<GIOHANG_PHIM> listphim = getInfo.listSP_PHIM;
        double tt = 0;
        model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        for (GIOHANG_PHIM giohang_phim : listphim) {
            model.addRow(new Object[]{giohang_phim.getPOSTER(), giohang_phim.getTEN_SAN_PHAM(), giohang_phim.getSO_LUONG(), formatter.format(giohang_phim.getGIA()) + " VNĐ", "X"});
            tt += giohang_phim.getGIA();
        }
        table.getColumnModel().getColumn(0).setCellRenderer(new DatVe.ImageRendererMovie());

        for (GIOHANG_DOAN giohang_doan : listDoAn) {
            model.addRow(new Object[]{giohang_doan.getHINH(), giohang_doan.getTEN_SAN_PHAM(), giohang_doan.getSO_LUONG() + " - " + giohang_doan.getKICH_CO(), formatter.format(giohang_doan.getGIA()) + " VNĐ", "X"});
            tt += giohang_doan.getGIA();
        }
        table.getColumnModel().getColumn(0).setCellRenderer(new DatVe.ImageRendererFood());
        table.getColumnModel().getColumn(4).setCellRenderer(r);
        KHHOME.Instance.sl.setText((listDoAn.size() + listphim.size()) + "");
        KHHOME.Instance.lbl.setText(formatter.format(tt) + " VNĐ");
    }

    DefaultTableCellRenderer r = new DefaultTableCellRenderer() {
        Font font = new Font("Segoe UI", Font.BOLD, 32);

        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus,
                    row, column);
            setOpaque(true);
            setFont(font);
            setHorizontalAlignment(RSButton.CENTER);
            setBackground(Color.WHITE);
            setForeground(Color.BLACK);
            return this;
        }

    };

    private class ImageRendererMovie extends DefaultTableCellRenderer {

        //add img into table
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            String photoname = String.valueOf(value);
            ImageIcon ImageIcon = new ImageIcon(
                    new ImageIcon("src/main/resources/com/qlrp/image/PHIM/POSTER/" + photoname).
                            getImage().getScaledInstance(70, 100, Image.SCALE_SMOOTH));
            //add border for img
            JLabel lb = new JLabel(ImageIcon);
            return lb;
        }
    }

    private class ImageRendererFood extends DefaultTableCellRenderer {

        //add img into table
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            String photoname = String.valueOf(value);
            ImageIcon ImageIcon = new ImageIcon(
                    new ImageIcon("src/main/resources/com/qlrp/image/PHIM/POSTER/" + photoname).
                            getImage().getScaledInstance(70, 100, Image.SCALE_SMOOTH));
            //add border for img
            JLabel lb = new JLabel(ImageIcon);
            return lb;
        }
    }

    private void addToListSP_PHIM() {
        GIOHANG_PHIM giohang = new GIOHANG_PHIM();

        giohang.setGIA(tongtien);
        giohang.setSO_LUONG(sp_SoLuong.getValue().hashCode() + "");
        giohang.setTEN_SAN_PHAM(phim.getTEN_PHIM());
        giohang.setNGAY_CHIEU(cbo_NgayChieu.getSelectedItem() + "");
        giohang.setGIO_CHIEU(cbo_GioChieu.getSelectedItem() + "");
        giohang.setPHONG_CHIEU(cbo_PhongChieu.getSelectedItem() + "");
        giohang.setGHE_NGOI(txt_GheNgoi.getText());
        giohang.setPOSTER(phim.getPOSTER());

        List<GIOHANG_PHIM> list = getInfo.listSP_PHIM;

        list.add(giohang);
        getInfo.listSP_PHIM = list;
    }

    private VEDAT getformToVeDat() {
        VEDAT vd = new VEDAT();
        vd.setMA_VE_DAT(lbl_MaVe.getText());
        if (Auth.cus == null) {
            vd.setSDT("0123456789");
        } else {
            vd.setSDT(Auth.cus.getSDT());
        }
        vd.setSO_LUONG(sp_SoLuong.getValue().hashCode());
        getInfo.listVEDAT.add(vd);
        return vd;
    }

    private void btn_ThemVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemVaoGioHangActionPerformed
        // TODO add your handling code here:
        try {
            if (validateForm()) {
                double tt = (giave * sp_SoLuong.getValue().hashCode()) + giaGhe;
                KHHOME.Instance.tienVe += tt;
                KHHOME.Instance.tongtien();
                for (String mg : MaGhe) {
                    GHENGOI ghengoi = qlghengoidao.selecteGhe_Ngoi(suatchieu.getMA_PHONG_CHIEU(), mg);
                    ghengoi.setDA_CHON(true);
                    qlghengoidao.update(ghengoi, suatchieu.getMA_PHONG_CHIEU());
                }
                addToListSP_PHIM();
                fillToCart(KHHOME.Instance.table);
                VEDAT vd = getformToVeDat();
                qlvedatdao.insert(vd);
                JOptionPane.showMessageDialog(this, "THÊM THÀNH CÔNG!", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                this.setVisible(false);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_ThemVaoGioHangActionPerformed

    private void sp_SoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sp_SoLuongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sp_SoLuongKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatVe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatVe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatVe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatVe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_ChonGheNgoi;
    private rojerusan.RSMaterialButtonRectangle btn_ThemVaoGioHang;
    private rojerusan.RSComboMetro cbo_GioChieu;
    private rojerusan.RSComboMetro cbo_NgayChieu;
    private rojerusan.RSComboMetro cbo_PhongChieu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_DinhDangPhim;
    private javax.swing.JLabel lbl_GiaVe;
    private javax.swing.JLabel lbl_HinhFilm;
    private javax.swing.JLabel lbl_MaVe;
    private javax.swing.JPanel pnl_KhoiChieu;
    private javax.swing.JPanel pnl_KhoiChieu1;
    private javax.swing.JPanel pnl_KhoiChieu2;
    private javax.swing.JPanel pnl_KhoiChieu3;
    private javax.swing.JPanel pnl_KhoiChieu5;
    private javax.swing.JPanel pnl_KhoiChieu6;
    private javax.swing.JPanel pnl_KhoiChieu7;
    private javax.swing.JPanel pnl_KhoiChieu8;
    private javax.swing.JSpinner sp_SoLuong;
    private javax.swing.JTextPane txt_GheNgoi;
    private javax.swing.JTextPane txt_Tenfilm;
    // End of variables declaration//GEN-END:variables
}
