/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlrp.ui;

import com.qlrp.dao.QLHOADONDAO;
import com.qlrp.entity.HOADON;
import com.qlrp.utils.MsgBox;
import com.qlrp.utils.getInfo;
import java.awt.Color;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author pc
 */
public class HOADONui extends javax.swing.JFrame {

    /**
     * Creates new form HOADONui
     */
    File f = new File("");
    QLHOADONDAO qlhoadondao = new QLHOADONDAO();
    List<HOADON> listHD = qlhoadondao.selectAll();
    
    public HOADONui() {
        initComponents();
    }
    
     private void init() {
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
     }
     
     public void fillToForm() {
        HOADON hd = getInfo.hd;
        if (hd != null) {
            txt_MaHD.setText(hd.getMAHOADON());
            txt_MaNV.setText(hd.getMANHANVIEN());
            txt_MaVe.setText(hd.getMAVE());
            txt_SDT.setText(hd.getSDT());
            dc_ngayban.setDate(hd.getNGAYBAN());  
        }
    }
     
     private void clearAll() {
        txt_MaHD.setText("");
        txt_MaNV.setText("");
        txt_MaVe.setText("");
        txt_SDT.setText("");
        dc_ngayban.setDate(null);
    }
     
     public void setForm(HOADON hd) {
        try {
            txt_MaHD.setText(hd.getMAHOADON());
            txt_MaNV.setText(hd.getMANHANVIEN());
            txt_MaVe.setText(hd.getMAVE());
            txt_SDT.setText(hd.getSDT());
            dc_ngayban.setDate(hd.getNGAYBAN());
        } catch (Exception e) {
        }
    }
     
    String mahoadon;

    private HOADON getForm() {
        HOADON hd = new HOADON();
        if (validateForm()) {
            hd.setMAHOADON(txt_MaHD.getText());
            hd.setMANHANVIEN(txt_MaNV.getText());
            hd.setMAVE(txt_MaVe.getText());
            hd.setSDT(txt_SDT.getText());
            hd.setNGAYBAN(dc_ngayban.getDate());
        } else {
            return null;
        }
        return hd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        txt_MaNV = new javax.swing.JTextField();
        txt_MaVe = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        dc_ngayban = new newscomponents.RSDateChooserModern();
        btn_QLHD_OK = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("HÓA ĐƠN");

        jLabel2.setText("MÃ HÓA ĐƠN :");

        jLabel3.setText("MÃ NHÂN VIÊN :");

        jLabel4.setText("MÃ VÉ :");

        jLabel5.setText("SỐ ĐIỆN THOẠI :");

        jLabel6.setText("NGÀY BÁN :");

        txt_MaHD.setEditable(false);

        txt_MaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaVeActionPerformed(evt);
            }
        });

        dc_ngayban.setBackground(new java.awt.Color(102, 102, 255));

        btn_QLHD_OK.setText("OK");
        btn_QLHD_OK.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_QLHD_OK.setkEndColor(new java.awt.Color(0, 112, 192));
        btn_QLHD_OK.setkHoverEndColor(new java.awt.Color(0, 30, 153));
        btn_QLHD_OK.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_QLHD_OK.setkHoverStartColor(new java.awt.Color(0, 30, 153));
        btn_QLHD_OK.setkPressedColor(new java.awt.Color(153, 153, 153));
        btn_QLHD_OK.setkStartColor(new java.awt.Color(0, 79, 174));
        btn_QLHD_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLHD_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_MaHD)
                            .addComponent(txt_MaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txt_MaVe)
                            .addComponent(txt_SDT)
                            .addComponent(dc_ngayban, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_QLHD_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txt_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(txt_MaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(dc_ngayban, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btn_QLHD_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaVeActionPerformed

    private void btn_QLHD_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLHD_OKActionPerformed
         if (btn_QLHD_OK.isEnabled()) {
            HOADON hd = getForm();
            if (hd != null) {
                if (qlhoadondao.selectebyID(hd.getMAHOADON()) != null) {
                    qlhoadondao.update(hd);
                    MsgBox.alert(this, "Cập nhật thành công!");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Hoa Don này không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            MsgBox.alert(this, "You can only Add. If you want to edit, please choose again!");
        }
        
    }//GEN-LAST:event_btn_QLHD_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOADONui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOADONui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOADONui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOADONui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOADONui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_QLHD_OK;
    private newscomponents.RSDateChooserModern dc_ngayban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_MaVe;
    private javax.swing.JTextField txt_SDT;
    // End of variables declaration//GEN-END:variables

    private boolean validateForm() {
       String Error = "";
        if (txt_MaNV.getText().equals("")) {
            Error += "MaNV không được trống! \n";           
        }
        
        if (txt_MaVe.getText().equals("")) {
            Error += "MaVe không được trống! \n";           
        }
        
        if (txt_SDT.getText().equals("")) {
            Error += "Số điện thoai không được trống! \n";           
        }
       
        if (dc_ngayban.getDate().equals(null)) {
            Error += "Ngày sản xuất phim trống! \n";
            dc_ngayban.setBorder(new MatteBorder(0, 0, 2, 0, Color.RED));
            dc_ngayban.grabFocus();
        }
        
        if (!Error.equals("")) {
            JOptionPane.showMessageDialog(this, Error, "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
}
