/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;

import com.qlrp.dao.QLDADAO;
import com.qlrp.dao.QLPHIMDAO;
import com.qlrp.entity.DOAN;
import com.qlrp.entity.PHIM;
import com.qlrp.utils.XImage;
import com.qlrp.utils.setUIJScroll;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.GridLayout;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;
import static java.lang.Thread.sleep;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author HAN-PC
 */
public class KHHOME extends javax.swing.JFrame{

    /**
     * Creates new form KHACHHANG_HOME
     */
    File file = new File("");
    QLPHIMDAO qlphimdao = new QLPHIMDAO();
    QLDADAO qldadao = new QLDADAO();
    
    List<PHIM> listfilm = null;
    List<DOAN> listDoAn = null;
    
    public KHHOME() {
        initComponents();
        setLocationRelativeTo(null);

        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_poster = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pnl_cart = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_SoLuong = new com.k33ptoo.components.KButton();
        txt_Search_Film = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbo_TheLoaiFilm = new javax.swing.JComboBox<>();
        cbo_QuocGia_Film = new javax.swing.JComboBox<>();
        cbo_QuocGia_Film1 = new javax.swing.JComboBox<>();
        btn_Avatar = new javax.swing.JButton();
        btn_Cart = new javax.swing.JButton();
        pnl_film = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnl_SlideFilm = new rojerusan.RSPanelsSlider();
        pnl_DoAn = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnl_slideDoAn = new rojerusan.RSPanelsSlider();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbo_LoaiDoAn = new javax.swing.JComboBox<>();
        txt_Search_DoAn = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel26 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextArea11 = new javax.swing.JTextArea();
        jTextArea12 = new javax.swing.JTextArea();
        jTextArea13 = new javax.swing.JTextArea();
        jTextArea14 = new javax.swing.JTextArea();
        jTextArea15 = new javax.swing.JTextArea();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbo_LoaiKhuyenMai = new javax.swing.JComboBox<>();
        txt_Search_KhuyenMai = new javax.swing.JTextField();
        jPanel35 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel38 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextArea21 = new javax.swing.JTextArea();
        jTextArea22 = new javax.swing.JTextArea();
        jTextArea23 = new javax.swing.JTextArea();
        jTextArea24 = new javax.swing.JTextArea();
        jTextArea25 = new javax.swing.JTextArea();
        pnl_KhuyenMai = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        pnl_slideKhuyenMai = new rojerusan.RSPanelsSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4TLIX CINEMAS");
        setResizable(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_poster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/video poster/poster2.gif"))); // NOI18N
        jPanel3.add(lbl_poster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_cart.setBackground(new java.awt.Color(255, 255, 255));
        pnl_cart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "SPIDER - NO WAY HOME", "100.000 VNĐ"},
                {null, "THOR 4 - LOVE AND THUNDER", "200.000 VNĐ"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "HÌNH", "TÊN SP", "GIÁ"
            }
        ));
        rSTableMetro1.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        rSTableMetro1.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        rSTableMetro1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rSTableMetro1.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rSTableMetro1.setRowHeight(60);
        jScrollPane2.setViewportView(rSTableMetro1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("GIỎ HÀNG");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("TỔNG TIỀN: 300.000 VNĐ");

        javax.swing.GroupLayout pnl_cartLayout = new javax.swing.GroupLayout(pnl_cart);
        pnl_cart.setLayout(pnl_cartLayout);
        pnl_cartLayout.setHorizontalGroup(
            pnl_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cartLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(pnl_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cartLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cartLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
            .addGroup(pnl_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_cartLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnl_cartLayout.setVerticalGroup(
            pnl_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnl_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cartLayout.createSequentialGroup()
                    .addContainerGap(49, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        jPanel7.add(pnl_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 450, 470));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_SoLuong.setText("2");
        btn_SoLuong.setEnabled(false);
        btn_SoLuong.setFocusable(false);
        btn_SoLuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_SoLuong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_SoLuong.setkAllowGradient(false);
        btn_SoLuong.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        btn_SoLuong.setkBorderRadius(110);
        btn_SoLuong.setkEndColor(new java.awt.Color(0, 153, 153));
        btn_SoLuong.setkHoverColor(new java.awt.Color(0, 153, 153));
        btn_SoLuong.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_SoLuong.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_SoLuong.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btn_SoLuong.setkIndicatorColor(new java.awt.Color(0, 153, 153));
        btn_SoLuong.setkPressedColor(new java.awt.Color(0, 153, 153));
        btn_SoLuong.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SoLuongActionPerformed(evt);
            }
        });
        jPanel5.add(btn_SoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 90, 30, 30));

        txt_Search_Film.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_Search_Film.setMargin(new java.awt.Insets(2, 10, 2, 6));
        jPanel5.add(txt_Search_Film, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 865, 42));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PHIM");

        cbo_TheLoaiFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "THỂ LOẠI", "HÀNH ĐỘNG", "HOẠT HÌNH", "PHIÊU LƯU", "KINH DỊ" }));

        cbo_QuocGia_Film.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QUỐC GIA", "VIỆT NAM", "MỸ", "TRUNG QUỐC", "NHẬT BẢN", "HÀN QUỐC" }));

        cbo_QuocGia_Film1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NGÀY KHỞI CHIẾU", "30/07/2022" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbo_TheLoaiFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cbo_QuocGia_Film, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cbo_QuocGia_Film1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbo_QuocGia_Film, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbo_TheLoaiFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbo_QuocGia_Film1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 810, -1));

        btn_Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/9311412861606062171-128.png"))); // NOI18N
        btn_Avatar.setBorder(null);
        btn_Avatar.setBorderPainted(false);
        btn_Avatar.setContentAreaFilled(false);
        btn_Avatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Avatar.setFocusPainted(false);
        jPanel5.add(btn_Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, 130));

        btn_Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/icons8_add_shopping_cart_70px.png"))); // NOI18N
        btn_Cart.setBorder(null);
        btn_Cart.setBorderPainted(false);
        btn_Cart.setContentAreaFilled(false);
        btn_Cart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cart.setFocusPainted(false);
        btn_Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CartActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 77, 74));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1359, 139));

        pnl_film.setBackground(new java.awt.Color(255, 255, 255));
        pnl_film.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/prev_48px.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setFocusPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        pnl_film.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 50));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/next_48px (2).png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusPainted(false);
        pnl_film.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 110, -1, 50));

        jScrollPane3.setBorder(null);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jScrollPane3AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseMoved(evt);
            }
        });

        pnl_SlideFilm.setBackground(new java.awt.Color(255, 255, 255));
        pnl_SlideFilm.setLayout(new java.awt.GridLayout(1, 0, 56, 0));
        jScrollPane3.setViewportView(pnl_SlideFilm);

        pnl_film.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1280, 320));

        jPanel7.add(pnl_film, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1360, 330));

        pnl_DoAn.setBackground(new java.awt.Color(255, 255, 255));
        pnl_DoAn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/prev_48px.png"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setFocusPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        pnl_DoAn.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 50));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/next_48px (2).png"))); // NOI18N
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setFocusPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        pnl_DoAn.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 120, -1, 50));

        jScrollPane4.setBorder(null);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pnl_slideDoAn.setBackground(new java.awt.Color(255, 255, 255));
        pnl_slideDoAn.setLayout(new java.awt.GridLayout(1, 0, 56, 0));
        jScrollPane4.setViewportView(pnl_slideDoAn);

        pnl_DoAn.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1280, 310));

        jPanel7.add(pnl_DoAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1360, 330));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("ĐỒ ĂN");

        cbo_LoaiDoAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOẠI ĐỒ ĂN", "ĐỒ ĂN", "ĐỒ UỐNG" }));

        txt_Search_DoAn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_Search_DoAn.setMargin(new java.awt.Insets(2, 10, 2, 6));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cbo_LoaiDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(txt_Search_DoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(txt_Search_DoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cbo_LoaiDoAn))
                .addContainerGap())
        );

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("ĐỒ ĂN");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOẠI ĐỒ ĂN", "ĐỒ ĂN", "ĐỒ UỐNG" }));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jComboBox4))
                .addContainerGap())
        );

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel21.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(null);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/prev_48px.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jPanel26.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 50));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/next_48px (2).png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jPanel26.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 100, -1, 50));

        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea11.setRows(2);
        jTextArea11.setTabSize(2);
        jTextArea11.setText("SPIDER - NO WAY HOME");
        jTextArea11.setWrapStyleWord(true);
        jTextArea11.setBorder(null);
        jTextArea11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel26.add(jTextArea11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 210, 60));

        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea12.setRows(2);
        jTextArea12.setTabSize(2);
        jTextArea12.setText("EVERYTHING EVERYWHRE\n\t   ALL OF ONCE");
        jTextArea12.setWrapStyleWord(true);
        jTextArea12.setBorder(null);
        jTextArea12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel26.add(jTextArea12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 60));

        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea13.setRows(2);
        jTextArea13.setTabSize(2);
        jTextArea13.setText("THOR 4 - LOVE AND \n        THUNDER");
        jTextArea13.setWrapStyleWord(true);
        jTextArea13.setBorder(null);
        jTextArea13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel26.add(jTextArea13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 170, 60));

        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea14.setRows(2);
        jTextArea14.setTabSize(2);
        jTextArea14.setText("MINIONS : RISE OF GRU");
        jTextArea14.setWrapStyleWord(true);
        jTextArea14.setBorder(null);
        jTextArea14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel26.add(jTextArea14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 200, 40));

        jTextArea15.setColumns(20);
        jTextArea15.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea15.setRows(2);
        jTextArea15.setTabSize(2);
        jTextArea15.setText("TOP GUN MAVERICK");
        jTextArea15.setWrapStyleWord(true);
        jTextArea15.setBorder(null);
        jTextArea15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel26.add(jTextArea15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 240, 170, 60));

        jScrollPane5.setViewportView(jPanel26);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel21.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel7.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 510, 1359, 70));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("KHUYẾN MÃI");

        cbo_LoaiKhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOẠI KHUYẾN MÃI", "COMBO", "VÉ PHIM", "ĐỒ ĂN" }));

        txt_Search_KhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_Search_KhuyenMai.setMargin(new java.awt.Insets(2, 10, 2, 6));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(cbo_LoaiKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(txt_Search_KhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addComponent(txt_Search_KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cbo_LoaiKhuyenMai))
                .addContainerGap())
        );

        jPanel33.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel33.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(null);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/prev_48px.png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusPainted(false);
        jPanel38.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 50));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/next_48px (2).png"))); // NOI18N
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setFocusPainted(false);
        jPanel38.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 100, -1, 50));

        jTextArea21.setColumns(20);
        jTextArea21.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea21.setRows(2);
        jTextArea21.setTabSize(2);
        jTextArea21.setText("SPIDER - NO WAY HOME");
        jTextArea21.setWrapStyleWord(true);
        jTextArea21.setBorder(null);
        jTextArea21.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel38.add(jTextArea21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 210, 60));

        jTextArea22.setColumns(20);
        jTextArea22.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea22.setRows(2);
        jTextArea22.setTabSize(2);
        jTextArea22.setText("EVERYTHING EVERYWHRE\n\t   ALL OF ONCE");
        jTextArea22.setWrapStyleWord(true);
        jTextArea22.setBorder(null);
        jTextArea22.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel38.add(jTextArea22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 60));

        jTextArea23.setColumns(20);
        jTextArea23.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea23.setRows(2);
        jTextArea23.setTabSize(2);
        jTextArea23.setText("THOR 4 - LOVE AND \n        THUNDER");
        jTextArea23.setWrapStyleWord(true);
        jTextArea23.setBorder(null);
        jTextArea23.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel38.add(jTextArea23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 170, 60));

        jTextArea24.setColumns(20);
        jTextArea24.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea24.setRows(2);
        jTextArea24.setTabSize(2);
        jTextArea24.setText("MINIONS : RISE OF GRU");
        jTextArea24.setWrapStyleWord(true);
        jTextArea24.setBorder(null);
        jTextArea24.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel38.add(jTextArea24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 200, 40));

        jTextArea25.setColumns(20);
        jTextArea25.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jTextArea25.setRows(2);
        jTextArea25.setTabSize(2);
        jTextArea25.setText("TOP GUN MAVERICK");
        jTextArea25.setWrapStyleWord(true);
        jTextArea25.setBorder(null);
        jTextArea25.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel38.add(jTextArea25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 240, 170, 60));

        jScrollPane7.setViewportView(jPanel38);

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel33.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel7.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 945, 1359, 70));

        pnl_KhuyenMai.setBackground(new java.awt.Color(255, 255, 255));
        pnl_KhuyenMai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/prev_48px.png"))); // NOI18N
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.setFocusPainted(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        pnl_KhuyenMai.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 50));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlrp/image/KHHome/icon/next_48px (2).png"))); // NOI18N
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setFocusPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        pnl_KhuyenMai.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 140, -1, 50));

        jScrollPane8.setBorder(null);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pnl_slideKhuyenMai.setBackground(new java.awt.Color(255, 255, 255));
        pnl_slideKhuyenMai.setLayout(new java.awt.GridLayout(1, 0, 56, 0));
        jScrollPane8.setViewportView(pnl_slideKhuyenMai);

        pnl_KhuyenMai.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1280, 310));

        jPanel7.add(pnl_KhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1020, 1360, 340));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        this.setIconImage(XImage.getAppIcon());
//        setImageFilm();
        setPlaceHolder(txt_Search_Film, "Nhập để tìm kiếm...");
        setPlaceHolder(txt_Search_DoAn, "Nhập để tìm kiếm...");
        setPlaceHolder(txt_Search_KhuyenMai, "Nhập để tìm kiếm...");
        pnl_cart.setVisible(false);
//        setImageSlide();
        RunSlide();
        CustomUIJScroll(jScrollPane1);
        CustomUIJScroll(jScrollPane2);
        CustomUIJScroll(jScrollPane3);
        CustomUIJScroll(jScrollPane4);
        CustomUIJScroll(jScrollPane5);
        CustomUIJScroll(jScrollPane7);
        
        //Đổ dữ liệu lên form KHHome
        FillToPanelFilm();
        FillToPanelDoAn();
    }
    
    int i = 1;
    String duongdanBanner = "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\video poster\\";
    File f = new File("");
//    private void setImageSlide() {
//        File f = new File("");
//        String duongdanBanner = "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\video poster\\";
//        lbl_poster.setIcon(new ImageIcon(f.getAbsolutePath() + duongdanBanner + "poster" + i + ".jpg"));
//    }

    public void refeshForm() {
        jScrollPane3.getHorizontalScrollBar().setValue(0);
        jScrollPane4.getHorizontalScrollBar().setValue(0);
        jScrollPane8.getHorizontalScrollBar().setValue(0);
    }
    
    private void RunSlide() {
        Thread slideThread = new Thread() {
            @Override
            public void run() {
                try {
                    while (true) {

                        sleep(35000);
                        i++;
                        lbl_poster.setIcon(new ImageIcon(f.getAbsolutePath() + duongdanBanner + "poster" + i + ".gif"));
                        sleep(35000);
                        i++;
                        lbl_poster.setIcon(new ImageIcon(f.getAbsolutePath() + duongdanBanner + "poster" + i + ".gif"));
                        sleep(35000);
                        i++;
                        lbl_poster.setIcon(new ImageIcon(f.getAbsolutePath() + duongdanBanner + "poster" + i + ".gif"));
                        sleep(35000);
                        i = 1;
                    }
                } catch (Exception e) {
                }
            }
        };
        slideThread.start();
    }
    
    private void CustomUIJScroll(JScrollPane jscroll) {
        jscroll.getVerticalScrollBar().setUI(new setUIJScroll());
        jscroll.getVerticalScrollBar().setUnitIncrement(16);
        jscroll.getVerticalScrollBar().setCursor(new Cursor(HAND_CURSOR));
    }
    
    private void FillToPanelFilm() {
        listfilm = qlphimdao.selectAll();
        for (int i = 0; i < listfilm.size(); i++) {
            JPanel pnl = new JPanel();
            pnl.setLayout(new GridLayout(2, 1));
            
            //TextPane chứa tiêu đề
            JTextPane textPane = new JTextPane();
            textPane.setText(listfilm.get(i).getTEN_PHIM());
            StyledDocument style = textPane.getStyledDocument();
            SimpleAttributeSet align = new SimpleAttributeSet();
            StyleConstants.setAlignment(align, StyleConstants.ALIGN_CENTER);
            style.setParagraphAttributes(0, style.getLength(), align, false);
            textPane.setPreferredSize(new Dimension(210, 100));
            Font  f2  = new Font("Segoe UI",  Font.BOLD, 17);
            textPane.setFont(f2);
            
            //Label chứa hình
            JLabel lbl = new JLabel();
            lbl.setSize(new Dimension(210, 250));
            lbl.setMinimumSize(new Dimension(210, 250));
            lbl.setPreferredSize(new Dimension(210, 250));
            lbl.setMaximumSize(new Dimension(210, 250));
            String duongdanPoster = f.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\PHIM\\POSTER\\";
            lbl.setIcon(XImage.ResizeImage(lbl.getWidth(), lbl.getHeight(), duongdanPoster + listfilm.get(i).getPOSTER()));
            pnl.add(lbl);
            pnl.add(textPane);
            pnl_SlideFilm.add(pnl);   
        }
        
    }
    
    private void FillToPanelDoAn() {
        listDoAn = qldadao.selectAll();
        for (int i = 0; i < listDoAn.size(); i++) {
            JPanel pnl = new JPanel();
            pnl.setLayout(new GridLayout(2, 1));
            
            //TextPane chứa tiêu đề
            JTextPane textPane = new JTextPane();
            textPane.setText(listDoAn.get(i).getTENDOAN());
            StyledDocument style = textPane.getStyledDocument();
            SimpleAttributeSet align = new SimpleAttributeSet();
            StyleConstants.setAlignment(align, StyleConstants.ALIGN_CENTER);
            style.setParagraphAttributes(0, style.getLength(), align, false);
            textPane.setPreferredSize(new Dimension(210, 100));
            Font  f2  = new Font("Segoe UI",  Font.BOLD, 17);
            textPane.setFont(f2);
            
            //Label chứa hình
            JLabel lbl = new JLabel();
            lbl.setSize(new Dimension(210, 250));
            lbl.setMinimumSize(new Dimension(210, 250));
            lbl.setPreferredSize(new Dimension(210, 250));
            lbl.setMaximumSize(new Dimension(210, 250));
            String duongdanPoster = f.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\DOAN\\";
            lbl.setIcon(XImage.ResizeImage(lbl.getWidth(), lbl.getHeight(), duongdanPoster + listDoAn.get(i).getHINH()));
            pnl.add(lbl);
            pnl.add(textPane);
            pnl_slideDoAn.add(pnl);   
        }
        
    }
    
    private void btn_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SoLuongActionPerformed

    private void btn_CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CartActionPerformed
        // TODO add your handling code here:
        if (!pnl_cart.isShowing()) {
            pnl_cart.setVisible(true);
        } else {
            pnl_cart.setVisible(false);
        }


    }//GEN-LAST:event_btn_CartActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jScrollPane3AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jScrollPane3AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3AncestorMoved

    private void jScrollPane3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseMoved
        // TODO add your handling code here:    
    }//GEN-LAST:event_jScrollPane3MouseMoved

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void setPlaceHolder(JTextField searchText, String text) {
        searchText.setText(text);
        searchText.setForeground(Color.GRAY);
        searchText.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (searchText.getText().equals(text)) {
                    searchText.setText("");
                    searchText.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (searchText.getText().isEmpty()) {
                    searchText.setForeground(Color.GRAY);
                    searchText.setText(text);
                }
            }
        });
    }

//    private void setImageFilm() {
//        //set image film
//        lbl_film1.setIcon(XImage.ResizeImage(lbl_film1.getWidth(), lbl_film1.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\film\\EVERYTHING EVERYWHERE ALL OF ONCE.jpg"));
//        lbl_film2.setIcon(XImage.ResizeImage(lbl_film2.getWidth(), lbl_film2.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\film\\THOR 4 - LOVE AND THUNDER.jpg"));
//        lbl_film3.setIcon(XImage.ResizeImage(lbl_film3.getWidth(), lbl_film3.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\film\\MINIONS RISE OF GRU.jpg"));
//        lbl_film4.setIcon(XImage.ResizeImage(lbl_film4.getWidth(), lbl_film4.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\film\\SPIDER - NO WAY HOME.jpg"));
//        lbl_film5.setIcon(XImage.ResizeImage(lbl_film5.getWidth(), lbl_film5.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\film\\Top_Gun_Maverick_Poster.jpg"));
//
//        //set image do an
//        lbl_DA1.setIcon(XImage.ResizeImage(lbl_DA1.getWidth(), lbl_DA1.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\do an\\coca.jpg"));
//        lbl_DA2.setIcon(XImage.ResizeImage(lbl_DA2.getWidth(), lbl_DA2.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\do an\\khoai tay chien.jpg"));
//        lbl_DA3.setIcon(XImage.ResizeImage(lbl_DA3.getWidth(), lbl_DA3.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\do an\\bap caramel.jpg"));
//        lbl_DA4.setIcon(XImage.ResizeImage(lbl_DA4.getWidth(), lbl_DA4.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\do an\\bap rang bo.jpg"));
//        lbl_DA5.setIcon(XImage.ResizeImage(lbl_DA5.getWidth(), lbl_DA5.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\do an\\pepsi.jpg"));
//
//        //set image khuyen mai
//        lbl_KM1.setIcon(XImage.ResizeImage(lbl_KM1.getWidth(), lbl_KM1.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\khuyen mai\\bap caramel.jpg"));
//        lbl_KM2.setIcon(XImage.ResizeImage(lbl_KM2.getWidth(), lbl_KM2.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\khuyen mai\\ticket ve don.jpg"));
//        lbl_KM3.setIcon(XImage.ResizeImage(lbl_KM3.getWidth(), lbl_KM3.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\khuyen mai\\pepsi.jpg"));
//        lbl_KM4.setIcon(XImage.ResizeImage(lbl_KM4.getWidth(), lbl_KM4.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\khuyen mai\\ticket ve doi.jpg"));
//        lbl_KM5.setIcon(XImage.ResizeImage(lbl_KM5.getWidth(), lbl_KM5.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\khuyen mai\\THOR 4 - LOVE AND THUNDER.jpg"));
//
////        lbl_poster.setIcon(XImage.ResizeImage(lbl_poster.getWidth(), lbl_poster.getHeight(), file.getAbsolutePath() + "\\src\\main\\resources\\com\\qlrp\\image\\KHHome\\video poster\\poster.gif"));
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHHOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Avatar;
    private javax.swing.JButton btn_Cart;
    private com.k33ptoo.components.KButton btn_SoLuong;
    private javax.swing.JComboBox<String> cbo_LoaiDoAn;
    private javax.swing.JComboBox<String> cbo_LoaiKhuyenMai;
    private javax.swing.JComboBox<String> cbo_QuocGia_Film;
    private javax.swing.JComboBox<String> cbo_QuocGia_Film1;
    private javax.swing.JComboBox<String> cbo_TheLoaiFilm;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_poster;
    private javax.swing.JPanel pnl_DoAn;
    private javax.swing.JPanel pnl_KhuyenMai;
    private rojerusan.RSPanelsSlider pnl_SlideFilm;
    private javax.swing.JPanel pnl_cart;
    private javax.swing.JPanel pnl_film;
    private rojerusan.RSPanelsSlider pnl_slideDoAn;
    private rojerusan.RSPanelsSlider pnl_slideKhuyenMai;
    private rojerusan.RSTableMetro rSTableMetro1;
    private javax.swing.JTextField txt_Search_DoAn;
    private javax.swing.JTextField txt_Search_Film;
    private javax.swing.JTextField txt_Search_KhuyenMai;
    // End of variables declaration//GEN-END:variables

}