/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;

import com.qlrp.dao.QLNVDAO;
import com.qlrp.dao.QLKHDAO;
import com.qlrp.entity.KHACHHANG;
import com.qlrp.entity.NHANVIEN;
import com.qlrp.utils.XImage;
import com.qlrp.utils.Auth;
import com.qlrp.utils.MsgBox;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.net.URL;
import javax.swing.UIManager;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author duong
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    File file = new File("");

    public login() {
        initComponents();
        init();
        this.setLocationRelativeTo(null);

    }

    private void init() {
        pnl_containerRight.setVisible(false);
        lbl_leftposter.setVisible(false);
        lbl_sologanLeft.setVisible(false);
        try {

            UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");

        } catch (Exception ex) {
        }
        this.setIconImage(XImage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_left = new keeptoo.KGradientPanel();
        pnl_containerLeft = new javax.swing.JPanel();
        btn_HidePass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Account = new javax.swing.JTextField();
        btn_Login = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_newAcc = new javax.swing.JButton();
        txt_Password = new javax.swing.JPasswordField();
        lbl_sologanLeft = new javax.swing.JLabel();
        lbl_leftposter = new javax.swing.JLabel();
        pnl_right = new keeptoo.KGradientPanel();
        pnl_containerRight = new javax.swing.JPanel();
        txtsdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtgmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtconfirm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        btndk = new javax.swing.JLabel();
        btn_TroLai = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbl_sologanRight = new javax.swing.JLabel();
        lbl_rightposter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4TLIX CINEMAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_left.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        pnl_left.setkEndColor(new java.awt.Color(255, 204, 255));
        pnl_left.setkGradientFocus(400);
        pnl_left.setkStartColor(new java.awt.Color(153, 153, 255));
        pnl_left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_containerLeft.setOpaque(false);

        btn_HidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/hide.png"))); // NOI18N
        btn_HidePass.setContentAreaFilled(false);
        btn_HidePass.setFocusPainted(false);
        btn_HidePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HidePassActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/user.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/padlock (4).png"))); // NOI18N

        txt_Account.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_Account.setToolTipText("");
        txt_Account.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_Account.setMargin(new java.awt.Insets(2, 20, 2, 6));
        txt_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AccountActionPerformed(evt);
            }
        });

        btn_Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LoginMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ĐĂNG NHẬP");

        javax.swing.GroupLayout btn_LoginLayout = new javax.swing.GroupLayout(btn_Login);
        btn_Login.setLayout(btn_LoginLayout);
        btn_LoginLayout.setHorizontalGroup(
            btn_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_LoginLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        btn_LoginLayout.setVerticalGroup(
            btn_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QUÊN MẬT KHẨU?");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/logo-4tlix2.png"))); // NOI18N

        btn_newAcc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_newAcc.setForeground(new java.awt.Color(255, 255, 255));
        btn_newAcc.setText("TẠO TÀI KHOẢN MỚI");
        btn_newAcc.setContentAreaFilled(false);
        btn_newAcc.setFocusPainted(false);
        btn_newAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newAccMouseExited(evt);
            }
        });
        btn_newAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newAccActionPerformed(evt);
            }
        });

        txt_Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Password.setToolTipText("");
        txt_Password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_Password.setMargin(new java.awt.Insets(2, 10, 2, 6));

        javax.swing.GroupLayout pnl_containerLeftLayout = new javax.swing.GroupLayout(pnl_containerLeft);
        pnl_containerLeft.setLayout(pnl_containerLeftLayout);
        pnl_containerLeftLayout.setHorizontalGroup(
            pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txt_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addGroup(pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                                    .addGap(210, 210, 210)
                                    .addComponent(btn_HidePass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(jLabel5))
                        .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(btn_newAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_containerLeftLayout.setVerticalGroup(
            pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)
                    .addGroup(pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1))
                        .addComponent(txt_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50)
                    .addGroup(pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnl_containerLeftLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(pnl_containerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(btn_HidePass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(10, 10, 10)
                    .addComponent(jLabel5)
                    .addGap(33, 33, 33)
                    .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btn_newAcc)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnl_left.add(pnl_containerLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 580));

        lbl_sologanLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/4TLIX_Slogantest.png"))); // NOI18N
        pnl_left.add(lbl_sologanLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 420, 210));

        lbl_leftposter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/right.png"))); // NOI18N
        lbl_leftposter.setText("jLabel12");
        pnl_left.add(lbl_leftposter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 450, 590));

        jPanel1.add(pnl_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 580));

        pnl_right.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        pnl_right.setkEndColor(new java.awt.Color(153, 153, 255));
        pnl_right.setkGradientFocus(800);
        pnl_right.setkStartColor(new java.awt.Color(255, 204, 255));
        pnl_right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_containerRight.setOpaque(false);

        txtsdt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtsdt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("SĐT");

        txtuser.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Họ tên");

        txtgmail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtgmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Email");

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Mật khẩu");

        txtconfirm.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtconfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nhập lại mật khẩu");

        kGradientPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kGradientPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kGradientPanel4MouseExited(evt);
            }
        });

        btndk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndk.setForeground(new java.awt.Color(255, 255, 255));
        btndk.setText("ĐĂNG KÝ");

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btndk)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndk, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        btn_TroLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_TroLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/left-arrow.png"))); // NOI18N
        btn_TroLai.setText("   TRỞ LẠI");
        btn_TroLai.setBorder(null);
        btn_TroLai.setBorderPainted(false);
        btn_TroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TroLaiActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/logo-4tlix.png"))); // NOI18N

        javax.swing.GroupLayout pnl_containerRightLayout = new javax.swing.GroupLayout(pnl_containerRight);
        pnl_containerRight.setLayout(pnl_containerRightLayout);
        pnl_containerRightLayout.setHorizontalGroup(
            pnl_containerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_containerRightLayout.createSequentialGroup()
                .addGroup(pnl_containerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_containerRightLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_containerRightLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(pnl_containerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addGroup(pnl_containerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtconfirm)
                                .addComponent(txtpass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtgmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtuser, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_containerRightLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(pnl_containerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_containerRightLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btn_TroLai, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnl_containerRightLayout.setVerticalGroup(
            pnl_containerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_containerRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TroLai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnl_right.add(pnl_containerRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 580));

        lbl_sologanRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/4TLIX_Slogantest.png"))); // NOI18N
        pnl_right.add(lbl_sologanRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 420, 210));

        lbl_rightposter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/left.png"))); // NOI18N
        pnl_right.add(lbl_rightposter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 450, 590));

        jPanel1.add(pnl_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HidePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HidePassActionPerformed
        // TODO add your handling code here:
        showPass();
    }//GEN-LAST:event_btn_HidePassActionPerformed

    private void txt_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AccountActionPerformed

    private void btn_TroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TroLaiActionPerformed
        // TODO add your handling code here:
        //Show panel container
        pnl_containerRight.setVisible(false);
        pnl_containerLeft.setVisible(true);

        //show sologan + poster
        lbl_sologanLeft.setVisible(false);
        lbl_leftposter.setVisible(false);
        lbl_sologanRight.setVisible(true);
        lbl_rightposter.setVisible(true);
    }//GEN-LAST:event_btn_TroLaiActionPerformed

    private void btn_newAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newAccActionPerformed
        // TODO add your handling code here:
        //Show panel container
        pnl_containerRight.setVisible(true);
        pnl_containerLeft.setVisible(false);

        //show sologan + poster
        lbl_sologanLeft.setVisible(true);
        lbl_leftposter.setVisible(true);
        lbl_sologanRight.setVisible(false);
        lbl_rightposter.setVisible(false);
    }//GEN-LAST:event_btn_newAccActionPerformed
    QLNVDAO qlnvdao = new QLNVDAO();
    QLKHDAO qlkhdao = new QLKHDAO();

    void dangNhap() {
        String tk = txt_Account.getText();
        String matKhau = txt_Password.getText();
        NHANVIEN epl = qlnvdao.selectebyID(tk);
        KHACHHANG cus = qlkhdao.selectebyID(tk);

        if (epl == null) {
            JOptionPane.showMessageDialog(this, "Sai tên đăng nhập!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
        } else if (!matKhau.equals(epl.getMAT_KHAU())) {
            JOptionPane.showMessageDialog(this, "Sai mật khẩu!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
        } else {
            MsgBox.alert(this, "ĐĂNG NHẬP THÀNH CÔNG!");
            SplashScreen sp = new SplashScreen();
            Auth.user = epl;
            sp.setVisible(true);
            this.setVisible(false);

        }
//        KHACHHANG cus = qlkhdao.selectebyID(tk);
//        if (cus == null ) {
//            JOptionPane.showMessageDialog(this, "Sai tên đăng nhập!", "Lỗi!!!!!!!!!!", JOptionPane.ERROR_MESSAGE);
//        } else if (!matKhau.equals(cus.getMAT_KHAU())) {
//            JOptionPane.showMessageDialog(this, "Sai mật khẩu!", "Lỗi!!!!!!!!!!", JOptionPane.ERROR_MESSAGE);
//        } else {
//            Auth.cus = cus;
//            MsgBox.alert(this, "Login successfully!");
////            this.dispose();
//        }
    }

    void dangKy() {
        int dk = JOptionPane.showConfirmDialog(this, "bạn có muốn đăng ký không?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (dk != JOptionPane.YES_OPTION) {
            return;
        }
//        try {
//            Class.forName(driver);
//            Connection con = DriverManager.getConnection(url, user, password);
//            String sql = "insert into NHANVIEN values (?,?,?,?,?)";
//            PreparedStatement ps = con.prepareStatement(sql);
//            ps.setString(1, txtsdt.getText());
//            ps.setString(2, txtuser.getText());
//            ps.setString(3, txtgmail.getText());
//            ps.setString(4, txtpass.getText());
//            ps.setString(5, txtconfirm.getText());
//
//            int n = ps.executeUpdate();
//
//            if (txtsdt.getText().equals("") | txtuser.getText().equals("") | txtgmail.getText().equals("") | txtpass.getText().equals("") | txtconfirm.getText().equals("")) {
//                JOptionPane.showMessageDialog(this, "không để thông tin trống");
//            } else if (n != 0) {
//                JOptionPane.showMessageDialog(this, "Đăng ký thành công");
//            } else {
//                JOptionPane.showMessageDialog(this, "Đăng ký thất bại");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }
    boolean isHidePass = true;
    File f = new File("");

    private void showPass() {
        String duongdanNHANVIEN = "\\src\\main\\resources\\com\\qlbh\\icon\\login\\";

        if (isHidePass) {
            txt_Password.setEchoChar((char) 0);
            btn_HidePass.setIcon(new ImageIcon(f.getAbsolutePath() + duongdanNHANVIEN + "view.png"));
            isHidePass = false;
        } else {
            txt_Password.setEchoChar('*');
            btn_HidePass.setIcon(new ImageIcon(f.getAbsolutePath() + duongdanNHANVIEN + "hide.png"));
            isHidePass = true;
        }
    }

    private void btn_LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LoginMouseEntered
        // TODO add your handling code here:
        jLabel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jLabel4.setForeground(Color.green);
    }//GEN-LAST:event_btn_LoginMouseEntered

    private void btn_LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LoginMouseExited
        // TODO add your handling code here:
        jLabel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_btn_LoginMouseExited

    private void btn_newAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newAccMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_newAccMouseClicked

    private void btn_newAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newAccMouseExited
        // TODO add your handling code here:
        btn_newAcc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_newAcc.setForeground(Color.white);
    }//GEN-LAST:event_btn_newAccMouseExited

    private void btn_newAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newAccMouseEntered
        // TODO add your handling code here:
        btn_newAcc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn_newAcc.setForeground(Color.red);
    }//GEN-LAST:event_btn_newAccMouseEntered

    private void kGradientPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel4MouseEntered
        // TODO add your handling code here:
        btndk.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btndk.setForeground(Color.green);
    }//GEN-LAST:event_kGradientPanel4MouseEntered

    private void kGradientPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel4MouseExited
        // TODO add your handling code here:
        btndk.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btndk.setForeground(Color.white);
    }//GEN-LAST:event_kGradientPanel4MouseExited

    private void btn_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LoginMouseClicked
        // TODO add your handling code here:
        dangNhap();
    }//GEN-LAST:event_btn_LoginMouseClicked

    private void kGradientPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel4MouseClicked
        // TODO add your handling code here:
        dangKy();

    }//GEN-LAST:event_kGradientPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HidePass;
    private keeptoo.KGradientPanel btn_Login;
    private javax.swing.JButton btn_TroLai;
    private javax.swing.JButton btn_newAcc;
    private javax.swing.JLabel btndk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel lbl_leftposter;
    private javax.swing.JLabel lbl_rightposter;
    private javax.swing.JLabel lbl_sologanLeft;
    private javax.swing.JLabel lbl_sologanRight;
    private javax.swing.JPanel pnl_containerLeft;
    private javax.swing.JPanel pnl_containerRight;
    private keeptoo.KGradientPanel pnl_left;
    private keeptoo.KGradientPanel pnl_right;
    private javax.swing.JTextField txt_Account;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txtconfirm;
    private javax.swing.JTextField txtgmail;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
