/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;

import com.qlrp.utils.XImage;
import java.io.File;

/**
 *
 * @author HAN-PC
 */
public class SendMail extends javax.swing.JFrame {

    /**
     * Creates new form SentMail
     */
//    ArrayList<SinhVien> listSV = new ArrayList<>();
//    File file = new File("");
//    String duongdan = file.getAbsolutePath() + "\\src\\Icons\\App\\iconframe.png";
//    String linkfile = "";
//    String duongdananh = "";
    public SendMail() {
        initComponents();

//        SinhVienImpl svi = new SinhVienImpl();
//        svi.doTuDataXuongList(listSV);
        this.setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        File f = new File("");
        try {
            String duongdanBanner = "\\src\\main\\resources\\com\\qlbh\\icon\\Employee\\ImageEmployee\\";
            lbl_Image.setIcon(XImage.ResizeImage(lbl_Image.getWidth(), lbl_Image.getHeight(), f.getAbsolutePath() + duongdanBanner + "Image-Default.png"));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Gmail = new javax.swing.JTextField();
        txt_Subject = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_To = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Message = new javax.swing.JTextArea();
        txt_LinkFile = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_ChonFile = new javax.swing.JButton();
        btn_Sending = new javax.swing.JButton();
        btn_SendAll = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        lbl_Image = new javax.swing.JLabel();
        btn_ChonFile1 = new javax.swing.JButton();

        setTitle("SEND MAIL");

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("MESSAGE:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("TO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("GMAIL:");

        txt_Gmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_Subject.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("SUBJECT:");

        txt_To.setColumns(20);
        txt_To.setRows(5);
        jScrollPane1.setViewportView(txt_To);

        txt_Message.setColumns(20);
        txt_Message.setRows(5);
        jScrollPane2.setViewportView(txt_Message);

        txt_LinkFile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("FILE:");

        btn_ChonFile.setText("CHOOSE FILE");
        btn_ChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonFileActionPerformed(evt);
            }
        });

        btn_Sending.setText("SENDING");
        btn_Sending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendingActionPerformed(evt);
            }
        });

        btn_SendAll.setText("SEND TO ALL STUDENTS");
        btn_SendAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendAllActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("PASSWORD:");

        txt_Password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lbl_Image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ImageMouseClicked(evt);
            }
        });

        btn_ChonFile1.setText("CHOOSE IMAGE");
        btn_ChonFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonFile1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_LinkFile, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btn_ChonFile)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_ChonFile1)))
                                .addGap(24, 24, 24)
                                .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Password))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_Gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_Subject, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btn_Sending, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_SendAll)))
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Gmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_LinkFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ChonFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Image, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sending, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SendAll, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendingActionPerformed
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            Properties p = new Properties();
//            p.put("mail.smtp.auth", "true");
//            p.put("mail.smtp.starttls.enable", "true");
//            p.put("mail.smtp.host", "smtp.gmail.com");
//            p.put("mail.smtp.port", 587);
//
//            //-----
//            String accountName = txt_Gmail.getText();
//            String accountPassword = txt_Password.getText();
//            Session s = Session.getInstance(p,
//                    new javax.mail.Authenticator() {
//                protected PasswordAuthentication getPasswordAuthentication() {
//                    return new PasswordAuthentication(accountName, accountPassword);
//                }
//            });
//            //--------
//            String from = txt_Gmail.getText();
//            String to = txt_To.getText();
//            String subject = txt_Subject.getText();
//            String body = txt_Message.getText();
//            Message msg = new MimeMessage(s);
//            msg.setFrom(new InternetAddress(from));
//            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
//            msg.setSubject(subject);
//            msg.setText(body);
//            //get file
//            Multipart multipart = new MimeMultipart();
//            if (!linkfile.equals("")) {
//                MimeBodyPart messageBodyFile = new MimeBodyPart();
//                // Duong dan den file cua ban
//                DataSource source1 = new FileDataSource(linkfile);
//                messageBodyFile.setDataHandler(new DataHandler(source1));
//                messageBodyFile.setFileName(linkfile);
//
//                multipart.addBodyPart(messageBodyFile);
//                msg.setContent(multipart);
//            }
//            if (!duongdananh.equals("")) {
//                // phan 3 chua tap tin image
//                MimeBodyPart messageBodyImage = new MimeBodyPart();
//                // Duong dan den file cua ban
//                DataSource source2 = new FileDataSource(duongdananh);
//                messageBodyImage.setDataHandler(new DataHandler(source2));
//                messageBodyImage.setFileName(duongdananh);
//
//                multipart.addBodyPart(messageBodyImage);
//                msg.setContent(multipart);
//            }
//            //-----------
//            Transport.send(msg);
//            JOptionPane.showMessageDialog(null, "Mail Đã được gửi thành công!", "Thông báo",
//                    JOptionPane.INFORMATION_MESSAGE);
//        } catch (MessagingException ex) {
//            Logger.getLogger(SendMail.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btn_SendingActionPerformed

    private void btn_ChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonFileActionPerformed
        // TODO add your handling code here:
//        try {
//            JFileChooser f = new JFileChooser(file.getAbsolutePath() + "\\src\\image");
//            f.setDialogTitle("Mở File");
//            f.showOpenDialog(null);
//
//            File link = f.getSelectedFile();
//            linkfile = link.getAbsolutePath();
//            txt_LinkFile.setText(linkfile);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_btn_ChonFileActionPerformed

    private void lbl_ImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ImageMouseClicked
        // TODO add your handling code here:
//        if (evt.getButton() == 1) {
//            try {
//                JFileChooser f = new JFileChooser(file.getAbsolutePath() + "\\src\\image");
//                f.setDialogTitle("Mở File");
//                f.showOpenDialog(null);
//
//                File fTenAnh = f.getSelectedFile();
//                duongdananh = fTenAnh.getAbsolutePath();
//                if (duongdananh != null) {
//                    lbl_Image.setIcon(ResizeImage(lbl_Image.getWidth(), lbl_Image.getHeight(), String.valueOf(duongdananh)));
//                    System.out.println(duongdananh);
//                } else {
//                    System.out.println("Bạn chưa chọn ảnh");
//                }
//            } catch (Exception e) {
//                System.out.println("Chưa chọn ảnh");
//                System.out.println(duongdananh);
//            }
//        }
    }//GEN-LAST:event_lbl_ImageMouseClicked

    private void btn_SendAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendAllActionPerformed
        // TODO add your handling code here:
//        String to = "";
//        for (int i = 0; i < listSV.size(); i++) {
//            if (i == listSV.size() - 1) {
//                to += listSV.get(i).getEmail();
//            } else {
//                to += listSV.get(i).getEmail() + ",";
//            }
//        }
//        try {
//            // TODO add your handling code here:
//            Properties p = new Properties();
//            p.put("mail.smtp.auth", "true");
//            p.put("mail.smtp.starttls.enable", "true");
//            p.put("mail.smtp.host", "smtp.gmail.com");
//            p.put("mail.smtp.port", 587);
//
//            //-----
//            String accountName = txt_Gmail.getText();
//            String accountPassword = txt_Password.getText();
//            Session s = Session.getInstance(p,
//                    new javax.mail.Authenticator() {
//                protected PasswordAuthentication getPasswordAuthentication() {
//                    return new PasswordAuthentication(accountName, accountPassword);
//                }
//            });
//            //--------
//            String from = txt_Gmail.getText();
//            String subject = txt_Subject.getText();
//            String body = txt_Message.getText();
//            Message msg = new MimeMessage(s);
//            msg.setFrom(new InternetAddress(from));
//            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
//            msg.setSubject(subject);
//            msg.setText(body);
//            //get file
//            Multipart multipart = new MimeMultipart();
//            if (!linkfile.equals("")) {
//                MimeBodyPart messageBodyFile = new MimeBodyPart();
//                // Duong dan den file cua ban
//                DataSource source1 = new FileDataSource(linkfile);
//                messageBodyFile.setDataHandler(new DataHandler(source1));
//                messageBodyFile.setFileName(linkfile);
//
//                multipart.addBodyPart(messageBodyFile);
//                msg.setContent(multipart);
//            }
//            if (!duongdananh.equals("")) {
//                // phan 3 chua tap tin image
//                MimeBodyPart messageBodyImage = new MimeBodyPart();
//                // Duong dan den file cua ban
//                DataSource source2 = new FileDataSource(duongdananh);
//                messageBodyImage.setDataHandler(new DataHandler(source2));
//                messageBodyImage.setFileName(duongdananh);
//
//                multipart.addBodyPart(messageBodyImage);
//                msg.setContent(multipart);
//            }
//            //-----------
//            Transport.send(msg);
//            JOptionPane.showMessageDialog(null, "Mail Đã được gửi thành công!", "Thông báo",
//                    JOptionPane.INFORMATION_MESSAGE);
//        } catch (MessagingException ex) {
//            Logger.getLogger(SendMail.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btn_SendAllActionPerformed

    private void btn_ChonFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonFile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ChonFile1ActionPerformed

//    public ImageIcon ResizeImage(int sizeWidth, int sizeHeight, String ImagePath) {
//        ImageIcon MyImage = new ImageIcon(ImagePath);
//        Image img = MyImage.getImage();
//        Image newImg = img.getScaledInstance(sizeWidth, sizeHeight, Image.SCALE_SMOOTH);
//        ImageIcon image = new ImageIcon(newImg);
//        return image;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChonFile;
    private javax.swing.JButton btn_ChonFile1;
    private javax.swing.JButton btn_SendAll;
    private javax.swing.JButton btn_Sending;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Image;
    private javax.swing.JTextField txt_Gmail;
    private javax.swing.JTextField txt_LinkFile;
    private javax.swing.JTextArea txt_Message;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Subject;
    private javax.swing.JTextArea txt_To;
    // End of variables declaration//GEN-END:variables
}
