/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlrp.ui;

import com.qlrp.utils.XImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author duong
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form splashloading
     */
    public SplashScreen() {
        initComponents();
        ImageIcon img = new ImageIcon("C:\\Users\\duong\\OneDrive\\Máy tính\\4TL_CINEMA\\src\\main\\resources\\com\\qlrp\\icon\\Sys\\Icon_app.png");
        this.setIconImage(XImage.getAppIcon());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4TLIX CINEMAS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(51, 51, 255));
        LoadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LoadingLabel.setText("LOADING...");
        jPanel1.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 280, 30));

        LoadingValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(51, 51, 255));
        LoadingValue.setText("0 %");
        jPanel1.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 30));

        LoadingBar.setForeground(new java.awt.Color(169, 224, 49));
        LoadingBar.setBorderPainted(false);
        LoadingBar.setFocusable(false);
        LoadingBar.setRequestFocusEnabled(false);
        LoadingBar.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/4tlix-logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 290, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/login/SPIDER-MAN- NO WAY HOME - Official Trailer (HD)_8.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);

//        try {
//            for (int row = 0; row <= 100; row++) {
//                Thread.sleep(100);
//                sp.LoadingValue.setText(Integer.toString(row) + "%");
//                sp.LoadingBar.setValue(row);
//                if (row == 100) {
//
//                    sp.setVisible(false);
//
////                    login.setVisible(true);
//                }
//            }
//        } catch (Exception e) {
//        }
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                sp.LoadingValue.setText(i + "%");

                if (i == 10) {
                    sp.LoadingLabel.setText("Turning On Module...");
                }
                if (i == 20) {
                    sp.LoadingLabel.setText("Loading On Module...");
                }
                if (i == 50) {
                    sp.LoadingLabel.setText("Connecting To The Database...");
                }
                if (i == 70) {
                    sp.LoadingLabel.setText("Connecting Successful...");
                }
                if (i == 90) {
                    sp.LoadingLabel.setText("Launching Application...");
                }
                sp.LoadingBar.setValue(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        sp.dispose();
        KHHOME kh = new KHHOME();
        kh.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
