/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlrp.ui;

/**
 *
 * @author pc
 */
public class THANHTOANui extends javax.swing.JFrame {

    /**
     * Creates new form THANHTOANui
     */
    public THANHTOANui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_THANHTOAN_HOTEN = new javax.swing.JTextField();
        txt_THANHTOAN_SDT = new javax.swing.JTextField();
        txt_THANHTOAN_CMND = new javax.swing.JTextField();
        txt_THANHTOAN_EMAIL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_THANHTOAN_DIACHI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_THANHTOAN = new javax.swing.JTable();
        btn_THANHTOAN_HUY = new com.k33ptoo.components.KButton();
        btn_THANHTOAN_THANHTOAN = new com.k33ptoo.components.KButton();
        btn_THANHTOAN_INVE = new com.k33ptoo.components.KButton();
        btn_THANHTOAN_INHOADON = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THANH TOÁN");

        jLabel2.setText("HỌ VÀ TÊN KHÁCH HÀNG :");

        jLabel3.setText("SỐ ĐIỆN THOẠI :");

        jLabel4.setText("CCCD/CMND KHÁCH HÀNG :");

        jLabel5.setText("EMAIL KHÁCH HÀNG :");

        jLabel6.setText("ĐỊA CHỈ KHÁCH HÀNG :");

        tbl_THANHTOAN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ HD", "MÃ NV", "MÃ VÉ", "TÊN ĐỒ ĂN", "SDT", "NGÀY BÁN"
            }
        ));
        jScrollPane1.setViewportView(tbl_THANHTOAN);

        btn_THANHTOAN_HUY.setText("HỦY");
        btn_THANHTOAN_HUY.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_THANHTOAN_HUY.setkEndColor(new java.awt.Color(0, 112, 192));
        btn_THANHTOAN_HUY.setkHoverEndColor(new java.awt.Color(0, 30, 153));
        btn_THANHTOAN_HUY.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_THANHTOAN_HUY.setkHoverStartColor(new java.awt.Color(0, 30, 153));
        btn_THANHTOAN_HUY.setkPressedColor(new java.awt.Color(153, 153, 153));
        btn_THANHTOAN_HUY.setkStartColor(new java.awt.Color(0, 79, 174));
        btn_THANHTOAN_HUY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_THANHTOAN_HUYActionPerformed(evt);
            }
        });

        btn_THANHTOAN_THANHTOAN.setText("THANH TOÁN");
        btn_THANHTOAN_THANHTOAN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_THANHTOAN_THANHTOAN.setkEndColor(new java.awt.Color(0, 112, 192));
        btn_THANHTOAN_THANHTOAN.setkHoverEndColor(new java.awt.Color(0, 30, 153));
        btn_THANHTOAN_THANHTOAN.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_THANHTOAN_THANHTOAN.setkHoverStartColor(new java.awt.Color(0, 30, 153));
        btn_THANHTOAN_THANHTOAN.setkPressedColor(new java.awt.Color(153, 153, 153));
        btn_THANHTOAN_THANHTOAN.setkStartColor(new java.awt.Color(0, 79, 174));
        btn_THANHTOAN_THANHTOAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_THANHTOAN_THANHTOANActionPerformed(evt);
            }
        });

        btn_THANHTOAN_INVE.setText("IN VÉ");
        btn_THANHTOAN_INVE.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_THANHTOAN_INVE.setkEndColor(new java.awt.Color(0, 112, 192));
        btn_THANHTOAN_INVE.setkHoverEndColor(new java.awt.Color(0, 30, 153));
        btn_THANHTOAN_INVE.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_THANHTOAN_INVE.setkHoverStartColor(new java.awt.Color(0, 30, 153));
        btn_THANHTOAN_INVE.setkPressedColor(new java.awt.Color(153, 153, 153));
        btn_THANHTOAN_INVE.setkStartColor(new java.awt.Color(0, 79, 174));
        btn_THANHTOAN_INVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_THANHTOAN_INVEActionPerformed(evt);
            }
        });

        btn_THANHTOAN_INHOADON.setText("IN HÓA ĐƠN");
        btn_THANHTOAN_INHOADON.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_THANHTOAN_INHOADON.setkEndColor(new java.awt.Color(0, 112, 192));
        btn_THANHTOAN_INHOADON.setkHoverEndColor(new java.awt.Color(0, 30, 153));
        btn_THANHTOAN_INHOADON.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_THANHTOAN_INHOADON.setkHoverStartColor(new java.awt.Color(0, 30, 153));
        btn_THANHTOAN_INHOADON.setkPressedColor(new java.awt.Color(153, 153, 153));
        btn_THANHTOAN_INHOADON.setkStartColor(new java.awt.Color(0, 79, 174));
        btn_THANHTOAN_INHOADON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_THANHTOAN_INHOADONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_THANHTOAN_HOTEN)
                            .addComponent(txt_THANHTOAN_SDT)
                            .addComponent(txt_THANHTOAN_EMAIL)
                            .addComponent(txt_THANHTOAN_CMND)
                            .addComponent(txt_THANHTOAN_DIACHI, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_THANHTOAN_HUY, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_THANHTOAN_THANHTOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_THANHTOAN_INVE, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_THANHTOAN_INHOADON, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_THANHTOAN_HOTEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_THANHTOAN_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_THANHTOAN_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_THANHTOAN_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_THANHTOAN_DIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_THANHTOAN_HUY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_THANHTOAN_THANHTOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_THANHTOAN_INVE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_THANHTOAN_INHOADON, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_THANHTOAN_HUYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_THANHTOAN_HUYActionPerformed
       
    }//GEN-LAST:event_btn_THANHTOAN_HUYActionPerformed

    private void btn_THANHTOAN_THANHTOANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_THANHTOAN_THANHTOANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_THANHTOAN_THANHTOANActionPerformed

    private void btn_THANHTOAN_INVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_THANHTOAN_INVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_THANHTOAN_INVEActionPerformed

    private void btn_THANHTOAN_INHOADONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_THANHTOAN_INHOADONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_THANHTOAN_INHOADONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THANHTOANui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THANHTOANui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THANHTOANui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THANHTOANui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THANHTOANui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_THANHTOAN_HUY;
    private com.k33ptoo.components.KButton btn_THANHTOAN_INHOADON;
    private com.k33ptoo.components.KButton btn_THANHTOAN_INVE;
    private com.k33ptoo.components.KButton btn_THANHTOAN_THANHTOAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_THANHTOAN;
    private javax.swing.JTextField txt_THANHTOAN_CMND;
    private javax.swing.JTextField txt_THANHTOAN_DIACHI;
    private javax.swing.JTextField txt_THANHTOAN_EMAIL;
    private javax.swing.JTextField txt_THANHTOAN_HOTEN;
    private javax.swing.JTextField txt_THANHTOAN_SDT;
    // End of variables declaration//GEN-END:variables
}
